MODS.push({n:1,t:"Noções de logística e marketing",edital:"Noções elementares de marketing e logística",
alerta:"O edital cobra apenas \"noções elementares\". Não há detalhamento de SCM, estoques ou Incoterms no Anexo IV; este módulo cobre as noções conceituais mais prováveis.",
intro:"A Transpetro atua no transporte e armazenamento de petróleo, derivados, gás e biocombustíveis. Logística e marketing formam a base conceitual da atuação em comercialização. Por serem noções elementares, esperam-se definições, comparações entre conceitos e aplicações simples.",
obj:["Diferenciar logística de gestão da cadeia de suprimentos (SCM).","Identificar os fluxos da cadeia e o trade-off entre eficiência e responsividade.","Explicar o efeito chicote e suas causas.","Definir marketing, segmentação, posicionamento e o composto de marketing (4 Ps), ligando \"praça\" à logística."],
secs:[
["1. Logística × SCM","<p><b>Logística</b> é a parte do processo da cadeia que planeja, implementa e controla o fluxo e a armazenagem eficientes e eficazes de bens, serviços e informações, do ponto de origem ao ponto de consumo, para atender às exigências do cliente. <b>SCM</b> abrange o planejamento e a gestão de sourcing, compras, conversão e logística, incluindo a coordenação e colaboração com parceiros. <b>Logística é subconjunto da SCM.</b></p>","definições do CSCMP; BALLOU, R. H. <i>Gerenciamento da Cadeia de Suprimentos/Logística Empresarial</i>, Bookman; CHOPRA, S.; MEINDL, P. <i>Gestão da Cadeia de Suprimentos</i>, Pearson (cap. 1)."],
["2. Fluxos e elos","<p>Fluxos: físico, de informação e financeiro.</p><pre>UPSTREAM           MIDSTREAM                      DOWNSTREAM\nExploração e   →   Transporte (dutos, navios)  →  Refino → Distribuição\nprodução           e armazenagem (terminais)      → Varejo/consumidor</pre>","segmentação upstream/midstream/downstream é convenção de mercado, não definição legal nem do edital."],
["3. Estratégia, trade-off e direcionadores","<p>Objetivo da cadeia: maximizar o <b>excedente</b> (valor para o cliente menos custo da cadeia). Deve haver <b>ajuste estratégico</b> entre a estratégia competitiva e a da cadeia. Mais <b>responsividade</b> tende a elevar o custo; mais <b>eficiência</b> reduz a responsividade.</p><p>Direcionadores: instalações, estoque, transporte, informação, fontes de suprimento (sourcing) e preço.</p>","CHOPRA; MEINDL, <i>Gestão da Cadeia de Suprimentos</i>, caps. 1 a 3."],
["4. Efeito chicote (bullwhip)","<p>A variabilidade dos pedidos aumenta conforme se sobe na cadeia. Causas: (1) processamento da previsão de demanda; (2) formação de lotes; (3) flutuação de preços e promoções; (4) racionamento e jogo de escassez. Mitigação: compartilhar informação de demanda, reduzir lotes e prazos, estabilizar preços e colaborar.</p>","LEE, PADMANABHAN e WHANG, \"The Bullwhip Effect in Supply Chains\", <i>Sloan Management Review</i>, 1997."],
["5. Conceito de marketing","<p>Segundo a AMA (2017), marketing é a atividade, o conjunto de instituições e os processos para criar, comunicar, entregar e trocar ofertas que tenham valor para consumidores, clientes, parceiros e a sociedade em geral. Para Kotler, é o processo social e gerencial pelo qual pessoas e grupos obtêm o que necessitam e desejam por meio da criação, oferta e troca de produtos de valor.</p>","American Marketing Association (definição de 2017); KOTLER, P.; KELLER, K. <i>Administração de Marketing</i>, Pearson."],
["6. Segmentação, mercado-alvo e posicionamento (STP)","<ul><li><b>Segmentação:</b> dividir o mercado em grupos com necessidades, características ou comportamentos semelhantes.</li><li><b>Seleção de mercado-alvo:</b> escolher o(s) segmento(s) a atender.</li><li><b>Posicionamento:</b> definir a imagem e o valor da oferta na mente do cliente-alvo em relação aos concorrentes.</li></ul>","KOTLER; KELLER, <i>Administração de Marketing</i>."],
["7. Composto de marketing (4 Ps)","<table><tr><th>P</th><th>Decisões</th></tr><tr><td>Produto</td><td>Atributos, qualidade, variedade, serviços associados</td></tr><tr><td>Preço</td><td>Política de preços, descontos, prazos de pagamento</td></tr><tr><td>Praça (distribuição)</td><td>Canais, cobertura, localização, estoques e transporte: o elo com a logística</td></tr><tr><td>Promoção (comunicação)</td><td>Propaganda, vendas pessoais, promoção de vendas, relações públicas</td></tr></table>","McCARTHY, E. J. <i>Basic Marketing</i>, 1960 (origem dos 4 Ps); KOTLER; KELLER."]
],
mapa:`NOÇÕES DE LOGÍSTICA E MARKETING
├── Logística ⊂ SCM
├── Fluxos: físico | informação | financeiro
├── Trade-off: eficiência ⇄ responsividade
├── Direcionadores: instalações, estoque, transporte,
│                   informação, sourcing, preço
├── Efeito chicote: previsão, lotes, preços, racionamento
└── Marketing
    ├── Conceito (AMA / Kotler)
    ├── STP: segmentação → alvo → posicionamento
    └── 4 Ps: produto, preço, praça (⇄ logística), promoção`,
q:[
Q("Sobre a relação entre logística e gestão da cadeia de suprimentos (SCM), é correto afirmar que",["a logística é mais ampla que a SCM, pois abrange fornecedores e clientes finais.","a SCM restringe-se às atividades de transporte e armazenagem dentro da empresa.","a logística é parte da SCM, que também envolve coordenação e colaboração com parceiros da cadeia.","SCM e logística são sinônimos perfeitos em qualquer literatura.","a SCM trata apenas do fluxo financeiro entre elos da cadeia."],2,["Inverte a relação: a logística é subconjunto da SCM.","A SCM é interorganizacional, não se limita ao interior da empresa.","Logística ⊂ SCM, e a SCM inclui coordenação com parceiros.","Não são sinônimos perfeitos, embora o uso coloquial os misture.","A SCM integra fluxos físicos, de informação e financeiros."],"CSCMP; Ballou; Chopra e Meindl (cap. 1)."),
Q("O aumento da variabilidade dos pedidos à medida que se caminha do varejo em direção aos fornecedores é conhecido como efeito chicote. Uma medida coerente para reduzi-lo é",["aumentar o tamanho dos lotes de pedido para reduzir a frequência.","compartilhar dados de demanda ao longo da cadeia.","intensificar promoções sazonais de preço.","cada elo trabalhar exclusivamente com sua própria previsão isolada.","racionar o produto para forçar os clientes a anteciparem pedidos."],1,["Lotes maiores (batching) são causa do efeito chicote.","O compartilhamento de informação reduz a distorção da demanda.","Promoções e flutuações de preço são causa.","Previsões isoladas amplificam a distorção.","Racionamento e jogo de escassez são causa."],"Lee, Padmanabhan e Whang (1997)."),
Q("Segundo Chopra e Meindl, ao se optar por uma cadeia com alto nível de responsividade, espera-se, em regra,",["maior eficiência de custo, pois a responsividade elimina estoques e capacidade ociosa.","irrelevância do ajuste estratégico entre a estratégia da cadeia e a competitiva.","maior custo da cadeia, pois responsividade tende a exigir capacidade, estoque ou flexibilidade adicionais.","eliminação do trade-off entre custo e serviço.","redução automática do excedente da cadeia."],2,["Afirma o oposto do que o modelo prevê.","O ajuste estratégico é central no modelo.","Há trade-off entre responsividade e custo.","O trade-off existe justamente nesse ponto.","O excedente pode até aumentar se o valor gerado superar o custo adicional; não há redução automática."],"Chopra e Meindl, cap. 1."),
Q("Em marketing, o processo de dividir o mercado em grupos de consumidores com necessidades, características ou comportamentos semelhantes é denominado",["posicionamento.","segmentação.","promoção.","precificação.","distribuição."],1,["Posicionamento é definir a imagem e o valor da oferta na mente do cliente-alvo.","Segmentação é a divisão do mercado em grupos homogêneos.","Promoção é um dos 4 Ps (comunicação).","Precificação é o P de preço.","Distribuição é o P de praça."],"Kotler e Keller."),
Q("No composto de marketing (4 Ps), as decisões sobre canais de distribuição, cobertura de mercado, localização, estoques e transporte relacionam-se ao P de",["produto.","preço.","promoção.","praça.","posicionamento."],3,["Produto trata de atributos, qualidade e serviços associados.","Preço trata de política de preços, descontos e prazos.","Promoção trata de comunicação com o mercado.","Praça (place) engloba canais e logística de distribuição.","Posicionamento faz parte do STP, não do composto dos 4 Ps."],"McCarthy (1960); Kotler e Keller.")
]});
