MODS.push({n:2,t:"Petróleo, derivados, gás natural e biocombustíveis",edital:"Características do petróleo e derivados (GLP, gasolina, diesel); gás natural; biocombustíveis",
alerta:"Percentuais de mistura (etanol na gasolina, biodiesel no diesel) e faixas de classificação por °API mudam por norma. Confira os valores vigentes no CNPE/ANP antes da prova.",
intro:"A Transpetro movimenta petróleo, derivados, gás e biocombustíveis. O edital pede as características principais desses produtos, então o foco é composição, propriedades que distinguem cada um e como são obtidos.",
obj:["Calcular e interpretar o grau API.","Relacionar o refino às frações obtidas.","Distinguir GLP, gasolina e diesel (composição e indicadores como octanagem e cetano).","Diferenciar gás natural, GNL e GNC.","Explicar etanol e biodiesel."],
secs:[
["1. Petróleo: composição e grau API","<p>Mistura complexa de hidrocarbonetos (parafínicos, naftênicos e aromáticos), com compostos de enxofre, nitrogênio, oxigênio e metais em menor teor. O <b>grau API</b> mede a densidade: <code>°API = 141,5 / d(60°F/60°F) − 131,5</code>.</p><ul><li>A água tem 10 °API. Maior °API significa petróleo <b>menos denso</b> (mais leve), em geral de maior valor.</li><li>Classificação usual: leve, médio e pesado (os cortes exatos variam conforme o critério adotado).</li><li>Quanto ao enxofre: <b>doce</b> (baixo teor) e <b>azedo</b> (alto teor).</li></ul>","THOMAS, J. E. (org.). <i>Fundamentos de Engenharia de Petróleo</i>, Interciência; ANP."],
["2. Refino e frações","<p>A destilação atmosférica separa o petróleo por faixa de temperatura de ebulição, do mais leve ao mais pesado: gases, GLP, nafta/gasolina, querosene, diesel, gasóleos e resíduo. A destilação a vácuo processa o resíduo. O craqueamento catalítico (FCC) converte frações pesadas em frações mais leves e valiosas, como GLP e gasolina.</p>","THOMAS (org.); SZKLO, A.; ULLER, V. <i>Fundamentos do Refino de Petróleo</i>, Interciência."],
["3. GLP","<p>Gás liquefeito de petróleo: mistura predominantemente de <b>propano e butano</b>, obtida no refino e no processamento de gás natural. É armazenado <b>liquefeito sob pressão moderada</b>. É mais denso que o ar (vazamentos acumulam em pontos baixos) e, por ser inodoro, recebe odorizante (compostos de enxofre, como mercaptanas) para permitir a detecção.</p>","THOMAS (org.); ANP."],
["4. Gasolina","<p>Hidrocarbonetos de cadeia média (aproximadamente C5 a C12). A <b>octanagem</b> mede a resistência à detonação (knocking) em motores de ciclo Otto, usando como referência o isoctano (100) e o n-heptano (0). A gasolina automotiva brasileira leva <b>etanol anidro</b> em percentual definido por norma.</p>","THOMAS (org.); ANP (especificação e mistura vigentes)."],
["5. Óleo diesel","<p>Fração mais pesada que a gasolina, usada em motores de ignição por compressão (ciclo Diesel). O indicador de qualidade de ignição é o <b>índice de cetano</b>, que é o oposto conceitual da octanagem: quanto maior o cetano, mais fácil a autoignição. As variantes S10 e S500 indicam o teor máximo de enxofre (10 e 500 mg/kg). O diesel comercial recebe <b>biodiesel</b> em percentual definido por norma.</p>","THOMAS (org.); ANP."],
["6. Gás natural","<p>Mistura de hidrocarbonetos gasosos com predomínio do <b>metano</b>. Pode ser <b>associado</b> (produzido junto com o petróleo) ou <b>não associado</b>. O processamento em UPGN separa o gás seco (metano e etano) das frações mais pesadas, como o GLP. <b>GNL</b>: gás resfriado a cerca de −162 °C, quando vira líquido e reduz o volume em aproximadamente 600 vezes, facilitando o transporte marítimo. <b>GNC</b>: gás comprimido a alta pressão. A Lei 14.134/2021 é o marco legal atual do gás natural.</p>","THOMAS (org.); ANP; Lei 14.134/2021."],
["7. Biocombustíveis","<ul><li><b>Etanol</b>: obtido por fermentação de açúcares (no Brasil, principalmente cana-de-açúcar). O anidro é misturado à gasolina; o hidratado é usado puro.</li><li><b>Biodiesel</b>: ésteres obtidos por <b>transesterificação</b> de óleos vegetais ou gorduras animais com álcool (metanol ou etanol), com glicerina como coproduto.</li><li><b>RenovaBio</b> (Lei 13.576/2017): política de incentivo à descarbonização com metas para distribuidores e créditos de descarbonização (CBIOs).</li></ul>","Lei 13.576/2017; ANP; EPE."]
],
mapa:`PETRÓLEO E DERIVADOS
├── Petróleo: hidrocarbonetos; °API = 141,5/d − 131,5
│   └── maior °API = mais leve; água = 10 °API
├── Refino: destilação → gases, GLP, nafta, querosene, diesel, resíduo
├── GLP: propano + butano, liquefeito sob pressão
├── Gasolina: octanagem (Otto) + etanol anidro
├── Diesel: cetano (ignição por compressão), S10/S500 + biodiesel
├── Gás natural: metano; associado × não associado; GNL (−162 °C) × GNC
└── Biocombustíveis: etanol (fermentação), biodiesel (transesterificação)`,
q:[
Q("Um petróleo com densidade relativa (60°F/60°F) de 0,85 possui grau API mais próximo de",["25.","30.","35.","40.","45."],2,["141,5/0,85 − 131,5 ≈ 35; o valor 25 corresponde a densidade maior (cerca de 0,90).","Corresponderia a densidade de cerca de 0,876.","141,5/0,85 = 166,5; 166,5 − 131,5 = 35 °API.","Corresponderia a densidade de cerca de 0,825.","Corresponderia a densidade de cerca de 0,802."],"Definição de grau API (Thomas, Fundamentos de Engenharia de Petróleo)."),
Q("Sobre o GLP, é correto afirmar que é",["composto majoritariamente por metano e armazenado a −162 °C.","uma mistura de propano e butano, armazenada liquefeita sob pressão moderada.","produzido exclusivamente pela fermentação de açúcares.","menos denso que o ar, o que faz vazamentos se dissiparem para cima.","naturalmente odorizado, sem necessidade de aditivos."],1,["Descreve o GNL, não o GLP.","O GLP é de propano e butano, liquefeito sob pressão moderada.","A fermentação de açúcares gera etanol.","O GLP é mais denso que o ar e tende a se acumular em pontos baixos.","O GLP é inodoro e recebe odorizante para permitir a detecção de vazamentos."],"Thomas (org.); ANP."),
Q("A octanagem e o índice de cetano são indicadores de qualidade, respectivamente, de",["gasolina (resistência à detonação) e diesel (facilidade de autoignição).","diesel e gasolina, nessa ordem.","GLP e gás natural.","etanol e biodiesel, exclusivamente.","querosene de aviação e óleo combustível."],0,["A octanagem mede a resistência à detonação da gasolina; o cetano mede a qualidade de ignição por compressão do diesel.","Inverte os indicadores.","Não são indicadores usuais de GLP e gás natural.","São indicadores de gasolina e diesel, independentemente da origem do combustível.","Não são os indicadores clássicos desses produtos."],"Thomas (org.); ANP."),
Q("O GNL (gás natural liquefeito) caracteriza-se por",["ser gás natural comprimido a cerca de 200 bar.","ser resfriado a aproximadamente −162 °C, reduzindo drasticamente o volume para facilitar o transporte.","ser composto majoritariamente por propano e butano.","ser obtido por transesterificação de óleos vegetais.","não poder ser transportado por navios."],1,["Descreve o GNC.","A −162 °C o metano liquefaz e o volume cai cerca de 600 vezes.","Propano e butano compõem o GLP.","Transesterificação gera biodiesel.","O transporte marítimo em navios metaneiros é uma das principais aplicações do GNL."],"Thomas (org.); ANP."),
Q("O biodiesel é obtido, em regra, pelo processo de",["destilação fracionada do petróleo.","craqueamento catalítico de gasóleo.","transesterificação de óleos ou gorduras com álcool.","fermentação da cana-de-açúcar.","hidrogenação do gás natural."],2,["Destilação fracionada é etapa do refino do petróleo.","O craqueamento catalítico gera frações leves a partir de pesadas no refino.","Na transesterificação formam-se ésteres (biodiesel) e glicerina.","A fermentação da cana gera etanol.","Não é o processo que define o biodiesel."],"ANP; Lei 13.576/2017 (contexto do RenovaBio).")
]});
