MODS.push({n:3,t:"Transporte marítimo, afretamento e portos",edital:"Apoio portuário e agentes marítimos; afretamentos; portos e terminais; granéis líquidos; navegação regular e livre; avarias",
alerta:"O edital não detalha subtópicos. Faixas de porte de navios (DWT) e cláusulas de contratos-padrão variam por fonte; use como referência de ordem de grandeza.",
intro:"O transporte marítimo de petróleo e derivados é feito em petroleiros, contratados no mercado de afretamento. A Transpetro opera frota e terminais, e o edital cobra estrutura do mercado, tipos de navegação, avarias e apoio portuário.",
obj:["Diferenciar navegação regular e livre.","Explicar os principais tipos de afretamento e a lógica de frete, hire, laytime e demurrage.","Descrever o papel do agente marítimo e dos serviços de apoio portuário.","Definir avaria simples e avaria grossa.","Reconhecer a estrutura de portos e terminais de granéis líquidos."],
secs:[
["1. Navegação regular × livre","<ul><li><b>Regular (liner)</b>: linhas com rotas, escalas e frequência pré-definidas e tarifas publicadas. Típica de carga geral e contêineres.</li><li><b>Livre (tramp)</b>: sem rota nem calendário fixos; o navio vai onde a carga está, contratado por afretamento. Típica de granéis (petróleo, minérios, grãos). O transporte de petróleo bruto é predominantemente livre.</li></ul>","STOPFORD, M. <i>Maritime Economics</i>, Routledge; LUDOVICO, N. <i>Logística Internacional</i>, Saraiva."],
["2. Mercado de afretamento","<p>Agentes: <b>armador</b> (proprietário do navio), <b>afretador</b> (quem contrata o navio) e <b>corretor</b> (broker), que intermedeia. O mercado responde à oferta e demanda de tonelagem: o frete oscila com o ciclo de transporte, a disponibilidade de navios e o preço do combustível (bunker). Em petroleiros, o frete costuma ser cotado em escala de referência (Worldscale) ou em valor global (lump sum).</p><table><tr><th>Modalidade</th><th>Ideia</th></tr><tr><td>Por viagem (voyage charter)</td><td>Afretador paga o <b>frete</b> (por tonelada ou valor global) e o armador arca com a operação do navio, incluindo o combustível e, em regra, as despesas de porto</td></tr><tr><td>Por tempo (time charter)</td><td>Afretador paga o <b>hire</b> (diária) e, em regra, combustível e despesas portuárias; o armador mantém a gestão náutica</td></tr><tr><td>Casco nu (bareboat)</td><td>Afretador assume posse, tripulação e gestão do navio; equivale a um arrendamento</td></tr><tr><td>Contrato de volume (COA)</td><td>Compromisso de transportar volumes ao longo do tempo, com navios definidos a cada embarque</td></tr></table><p><b>Laytime</b> é o tempo permitido para carga/descarga. Se excedido, o afretador paga <b>demurrage</b> (sobre-estadia); se houver economia de tempo, pode haver <b>despatch</b>.</p>","STOPFORD; contratos-padrão de mercado (BIMCO, INTERTANKO); gestão náutica × comercial: conceito de mercado."],
["3. Petroleiros e granéis líquidos","<p>Classes usuais por porte: <b>VLCC</b> (aprox. 200 a 320 mil DWT), <b>Suezmax</b> (aprox. 120 a 200 mil), <b>Aframax</b> (aprox. 80 a 120 mil), <b>Panamax</b> e navios menores para derivados (produtos limpos). Os limites variam por fonte. A poluição por óleo é regulada pela Convenção MARPOL (Anexo I, óleo; Anexo II, substâncias líquidas nocivas a granel), que exige, entre outros, casco duplo, tanques de lastro segregado e lavagem com óleo cru (COW).</p>","STOPFORD; IMO (MARPOL 73/78)."],
["4. Portos e terminais","<p>No Brasil, a Lei 12.815/2013 distingue o <b>porto organizado</b> (bem público, com autoridade portuária e operadores portuários, e exploração por concessão ou arrendamento) do <b>terminal de uso privado (TUP)</b>, explorado por autorização. Terminais de granéis líquidos têm píeres, dolphins e boias de amarração (monobóias), com dutos ligando o navio aos tanques em terra. A ANTAQ regula a atividade portuária.</p>","Lei 12.815/2013; ANTAQ."],
["5. Apoio portuário e agente marítimo","<ul><li><b>Agente marítimo</b>: representa o armador ou afretador no porto, cuidando das formalidades com autoridades, provisões, coordenação dos serviços e documentação da escala.</li><li><b>Praticagem</b>: assessoria técnica local ao comandante para manobras seguras em zonas de praticagem (Lei 9.537/1997, LESTA).</li><li><b>Rebocadores, amarração, lanchas e fornecimento (supply, bunker)</b>: demais serviços de apoio.</li></ul>","Lei 9.537/1997; LUDOVICO."],
["6. Avarias marítimas","<ul><li><b>Avaria simples (particular)</b>: dano ou despesa suportado apenas pelo interessado que o sofreu (navio ou carga).</li><li><b>Avaria grossa (comum)</b>: sacrifício ou despesa <b>intencional e razoável</b> feito em favor da segurança comum da expedição, e que é rateado entre todos os interessados (navio, frete e carga). Regulada por regras como as de York-Antuérpia e pelo Código Comercial. Ex.: alijamento de carga para salvar o navio.</li></ul>","Código Comercial (Lei 556/1850, parte marítima); Regras de York-Antuérpia."]
],
mapa:`TRANSPORTE MARÍTIMO
├── Navegação: regular (liner, rota fixa) × livre (tramp, granéis)
├── Afretamento: viagem | tempo | casco nu | COA
│   └── frete/hire; laytime → demurrage / despatch
├── Petroleiros: VLCC, Suezmax, Aframax; MARPOL
├── Portos: organizado × TUP; terminais de granéis líquidos
├── Apoio: agente marítimo, praticagem, rebocadores
└── Avarias: simples (só quem sofreu) × grossa (rateada)`,
q:[
Q("A navegação em que o navio não tem rota nem calendário fixos, sendo contratado por afretamento para levar granéis como petróleo e minérios, denomina-se",["regular (liner).","livre (tramp).","de cabotagem exclusivamente.","interior.","de apoio marítimo."],1,["Na regular há rotas, escalas e frequência pré-definidas.","Na navegação livre (tramp) o navio segue a carga, contratado por afretamento.","Cabotagem refere-se à navegação entre portos do mesmo país; não é sinônimo de navegação livre.","Navegação interior é a realizada em hidrovias interiores.","Apoio marítimo atende plataformas e instalações offshore."],"Stopford, Maritime Economics."),
Q("No afretamento por tempo (time charter), o afretador",["assume a posse, a tripulação e toda a gestão do navio.","paga o hire e, em regra, o combustível e as despesas portuárias, enquanto o armador mantém a gestão náutica.","paga apenas um frete por tonelada e nada mais.","não tem qualquer direito de determinar a rota comercial do navio.","transfere ao armador todos os custos de combustível."],1,["Descreve o afretamento a casco nu (bareboat).","No time charter o afretador paga o hire e os custos de viagem; a gestão náutica permanece com o armador.","Descreve o afretamento por viagem.","No time charter o afretador dirige o emprego comercial do navio (rotas e cargas), dentro dos limites do contrato.","O combustível costuma ser custo do afretador no time charter."],"Stopford; contratos-padrão de mercado."),
Q("Diz-se que há demurrage quando",["a carga é rateada entre os interessados após sacrifício voluntário.","o afretador excede o tempo permitido para carga e descarga (laytime) e paga ao armador a sobre-estadia.","o armador entrega o navio sem tripulação.","o navio segue sem escala em rota regular.","o agente marítimo cobra taxa de praticagem."],1,["Descreve a avaria grossa.","Demurrage é a quantia paga pelo afretador ao armador pelo tempo que excede o laytime.","Descreve o afretamento a casco nu.","Não guarda relação com o conceito.","Não guarda relação com o conceito."],"Stopford; prática de mercado (BIMCO)."),
Q("A avaria grossa (comum) caracteriza-se por",["dano sofrido apenas pela carga, sem participação dos demais.","sacrifício ou despesa intencional e razoável em favor da segurança comum da expedição, rateado entre navio, frete e carga.","qualquer dano à carga, independentemente da causa.","despesas rotineiras de manutenção do navio.","multas aplicadas pela autoridade portuária."],1,["Descreve a avaria simples (particular).","A avaria grossa é o ato voluntário de sacrifício comum, rateado entre os interessados.","Danos comuns sem sacrifício intencional geralmente são avaria simples.","Manutenção rotineira é custo do armador.","Não é avaria."],"Código Comercial (parte marítima); Regras de York-Antuérpia."),
Q("O agente marítimo é o profissional ou empresa que",["representa o armador ou afretador no porto, cuidando das formalidades e serviços da escala.","assessora tecnicamente o comandante nas manobras em zonas de praticagem.","explora o terminal de uso privado por autorização.","determina o valor do frete nas bolsas de mercadorias.","fiscaliza a atividade portuária como agência reguladora."],0,["O agente marítimo atua como representante local do armador ou afretador.","Descreve o prático (praticagem).","Descreve o titular de um TUP.","Os fretes se formam no mercado, com participação de corretores.","Descreve a ANTAQ."],"Ludovico, Logística Internacional; Lei 9.537/1997.")
]});
