MODS.push({n:4,t:"Transporte dutoviário e regulação do setor (Lei 9.478/1997)",edital:"Transporte dutoviário; Lei 9.478/1997 e alterações; Portaria ANP nº 881/2022",
alerta:"<b>Lacuna:</b> não consegui ler a Portaria ANP nº 881/2022 e por isso este módulo não afirma o conteúdo dela. Leia o texto integral no site da ANP. Sobre a Lei 9.478/1997, confira também a redação atual dos arts. 56 a 65, alterados por leis posteriores (por exemplo, a Lei 14.134/2021, no que toca ao gás natural).",
intro:"A Transpetro tem origem legal na Lei do Petróleo. Este módulo trata do transporte por dutos (características técnicas) e do arcabouço regulatório: monopólio da União, ANP, CNPE, autorização de transporte e acesso de terceiros.",
obj:["Descrever tipos de dutos e vantagens/limitações do modal.","Explicar conceitos de batelada, interface e pig.","Situar o monopólio da União (CF, art. 177) e a possibilidade de contratação.","Reconhecer funções do CNPE e da ANP.","Diferenciar transporte de transferência e identificar a base legal da subsidiária de logística da Petrobras."],
secs:[
["1. Transporte dutoviário: conceitos","<ul><li><b>Oleoduto</b> (petróleo), <b>poliduto</b> (vários derivados, movimentados em bateladas), <b>gasoduto</b> (gás natural), além de minerodutos e alcooldutos.</li><li><b>Batelada</b>: lote de um produto empurrado pelo duto. A <b>interface</b> é a zona de mistura entre bateladas consecutivas, tratada no destino.</li><li><b>Pig</b>: dispositivo introduzido no duto para limpeza, separação de produtos ou inspeção.</li><li>Estações de <b>bombeamento</b> (líquidos) e de <b>compressão</b> (gás) mantêm a pressão e a vazão.</li><li>Tanques de teto flutuante reduzem perdas por evaporação de produtos voláteis nos terminais.</li></ul>","THOMAS (org.), <i>Fundamentos de Engenharia de Petróleo</i>; BALLOU, R. H. <i>Logística Empresarial</i> (comparação entre modais)."],
["2. Vantagens e limitações do modal dutoviário","<p><b>Vantagens:</b> baixo custo unitário em grandes volumes, operação contínua, segurança e baixa emissão. <b>Limitações:</b> alto investimento inicial, rota fixa (baixa flexibilidade), movimenta poucos tipos de produto e exige volumes elevados para justificar o investimento.</p>","BALLOU (características operacionais dos modais)."],
["3. Monopólio da União (CF, art. 177)","<p>Constituem monopólio da União, entre outros, a pesquisa e lavra de jazidas de petróleo e gás natural, a refinação, a importação e exportação de produtos, o transporte marítimo de petróleo bruto de origem nacional ou de derivados básicos produzidos no País e o transporte <b>por meio de conduto</b> de petróleo bruto, seus derivados e gás natural de qualquer origem. A União <b>pode contratar</b> com empresas estatais ou privadas essas atividades, observadas as condições da lei (art. 177, §1º).</p>","Constituição Federal, art. 177 e EC 9/1995."],
["4. Lei 9.478/1997: política, CNPE e ANP","<ul><li>Dispõe sobre a política energética nacional, as atividades do monopólio do petróleo, e institui o <b>CNPE</b> (Conselho Nacional de Política Energética), órgão de assessoramento da Presidência da República para formular políticas e diretrizes de energia, e a <b>ANP</b>.</li><li>A <b>ANP</b> é entidade integrante da Administração Federal indireta, sob regime de autarquia especial, vinculada ao Ministério de Minas e Energia. Sua finalidade é a regulação, a contratação e a fiscalização das atividades econômicas da indústria do petróleo, gás natural e biocombustíveis.</li></ul>","Lei 9.478/1997, arts. 1º, 2º, 7º e 8º."],
["5. Transporte × transferência; autorização; acesso; subsidiária","<ul><li><b>Transporte</b>: movimentação de petróleo, derivados ou gás natural em meio ou percurso de <b>interesse geral</b>. <b>Transferência</b>: movimentação em meio ou percurso de <b>interesse específico e exclusivo</b> do proprietário ou explorador das facilidades (Lei 9.478, art. 6º).</li><li>Empresas constituídas sob as leis brasileiras, com sede e administração no País, podem receber <b>autorização da ANP</b> para construir instalações e efetuar o transporte de petróleo, derivados e gás natural (art. 56).</li><li>Regra de <b>acesso de terceiros</b> aos dutos de transporte e terminais, mediante remuneração adequada ao titular das instalações (art. 58; confira a redação vigente).</li><li>A Petrobras deveria constituir <b>subsidiária</b> com atribuições de operar e construir seus dutos, terminais marítimos e embarcações para o transporte de petróleo, derivados e gás natural (art. 65). É a base legal da <b>Transpetro</b>.</li></ul>","Lei 9.478/1997, arts. 6º, 56, 58 e 65 (com alterações)."],
["6. Portaria ANP nº 881/2022","<p><b>Texto não verificado neste material.</b> Reserve tempo para ler a norma completa no site da ANP e produzir seu próprio resumo (objeto, definições, obrigações do agente regulado e prazos). Depois, use o simulado para testar a leitura.</p>","ANP, atos normativos (sítio oficial)."]
],
mapa:`DUTOS E REGULAÇÃO
├── Dutos: oleoduto | poliduto (bateladas, interface) | gasoduto
│   └── pig, bombeamento/compressão; alto CAPEX, baixo custo unitário
├── CF art. 177: conduto = monopólio da União; §1º: pode contratar
├── Lei 9.478/97
│   ├── CNPE: assessoria da Presidência (política energética)
│   ├── ANP: autarquia especial (MME); regula, contrata, fiscaliza
│   ├── Transporte (interesse geral) × Transferência (interesse específico)
│   ├── Autorização da ANP (art. 56); acesso de terceiros (art. 58)
│   └── Subsidiária da Petrobras para dutos/terminais/navios (art. 65)
└── Portaria ANP 881/2022: ler o texto oficial`,
q:[
Q("A ANP, criada pela Lei 9.478/1997, é",["órgão de assessoramento da Presidência da República para formular a política energética.","autarquia sob regime especial, vinculada ao Ministério de Minas e Energia, responsável pela regulação, contratação e fiscalização das atividades da indústria do petróleo, gás natural e biocombustíveis.","empresa pública que executa o monopólio do petróleo.","subsidiária integral da Petrobras.","órgão do Tribunal de Contas da União."],1,["Descreve o CNPE.","A ANP é autarquia especial vinculada ao MME, com funções de regulação, contratação e fiscalização.","O monopólio é da União, que pode contratar empresas estatais ou privadas; a ANP não é empresa pública executora.","A Petrobras é empresa (sociedade de economia mista); a ANP não é sua subsidiária.","A ANP integra a Administração Federal indireta, não o TCU."],"Lei 9.478/1997, arts. 2º, 7º e 8º."),
Q("A Lei 9.478/1997 previu que a Petrobras constituísse subsidiária com atribuições específicas de operar e construir seus dutos, terminais marítimos e embarcações para o transporte de petróleo, derivados e gás natural. Essa previsão é a base legal da",["ANP.","Transpetro.","CNPE.","EPE.","ANTAQ."],1,["A ANP é a agência reguladora.","A Transpetro é a subsidiária de logística da Petrobras (art. 65).","O CNPE formula políticas.","A EPE faz estudos e planejamento energético.","A ANTAQ regula transporte aquaviário e portos."],"Lei 9.478/1997, art. 65."),
Q("Segundo a Lei 9.478/1997, a movimentação de petróleo, derivados ou gás natural em meio ou percurso de interesse específico e exclusivo do proprietário ou explorador das facilidades é denominada",["transporte.","transferência.","distribuição.","revenda.","importação."],1,["Transporte refere-se a interesse geral.","Transferência é a movimentação de interesse específico e exclusivo do proprietário das facilidades.","Distribuição é a atividade de comercializar derivados a varejistas e consumidores.","Revenda é a venda ao consumidor final.","Importação é a entrada do produto no País."],"Lei 9.478/1997, art. 6º."),
Q("Em um poliduto que movimenta diferentes derivados em sequência, a zona de mistura entre dois lotes consecutivos é chamada de",["pig.","interface.","batelada.","estação de compressão.","monobóia."],1,["Pig é dispositivo de limpeza/inspeção.","Interface é a mistura entre bateladas consecutivas.","Batelada é o lote de um produto.","Compressão é etapa de gasodutos.","Monobóia é ponto de amarração de navios em terminais."],"Thomas (org.)."),
Q("Considerando a Constituição Federal, o transporte, por meio de conduto, de petróleo bruto, seus derivados e gás natural de qualquer origem",["é atividade livre, sem qualquer vínculo com o monopólio da União.","constitui monopólio da União, que pode contratar empresas estatais ou privadas nos termos da lei.","é de competência exclusiva dos Municípios.","é privativo da Petrobras, sem possibilidade de contratação.","é regulado exclusivamente pela ANTAQ."],1,["O transporte por conduto integra o rol do monopólio da União (art. 177).","O art. 177 inclui o transporte por conduto no monopólio, e o §1º permite a contratação com empresas estatais ou privadas.","Não é competência municipal.","Após a EC 9/1995, a União pode contratar com outras empresas.","A ANTAQ regula transporte aquaviário; a regulação do setor de petróleo é da ANP."],"CF, art. 177 e §1º.")
]});
