MODS.push({n:5,t:"Contratação nas estatais: Lei 13.303/2016 e LC 123/2006",edital:"Lei 13.303/2016, arts. 28 a 91; LC 123/2006, arts. 42 a 49; LC 147/2014",
alerta:"Tópico de alta relevância para a ênfase (fiscalização de contratos). <b>Não consegui acessar o texto oficial</b>: numeração de artigos, valores e prazos vêm do meu conhecimento prévio. Leia os artigos 28 a 91 na íntegra e confirme cada número citado aqui. Valores em reais podem ter sido atualizados.",
intro:"A Transpetro, como subsidiária de sociedade de economia mista, contrata bens e serviços pelo Estatuto das Estatais (Lei 13.303/2016) e por seu regulamento interno de licitações e contratos. O edital cobra os arts. 28 a 91 da lei e os arts. 42 a 49 da LC 123/2006.",
obj:["Identificar quando a licitação é exigida, dispensada ou inexigível.","Reconhecer os princípios e as fases do procedimento.","Listar critérios de julgamento, regimes de execução e procedimentos auxiliares.","Conhecer regras sobre contratos: garantia, duração, alteração e sanções.","Aplicar o tratamento favorecido a ME e EPP (LC 123)."],
secs:[
["1. Regra geral e exceções (art. 28)","<p>Contratos com terceiros para obras, serviços, compras, alienações e locações são <b>precedidos de licitação</b>, ressalvadas as hipóteses de dispensa (art. 29) e inexigibilidade (art. 30). No art. 28, §3º, as empresas ficam <b>dispensadas da observância do capítulo</b> quando: (I) comercializam, prestam ou executam de forma direta produtos, serviços ou obras <b>especificamente relacionados com seus objetos sociais</b>; (II) a escolha do parceiro está associada a suas características particulares, vinculada a oportunidades de negócio definidas e específicas, com inviabilidade de procedimento competitivo justificada.</p>","Lei 13.303/2016, art. 28 (caput e §3º)."],
["2. Dispensa e inexigibilidade (arts. 29 e 30)","<ul><li><b>Dispensa (art. 29)</b>: a competição seria possível, mas a lei autoriza contratar diretamente. Exemplos: obras e serviços de engenharia de pequeno valor (na redação original, até R$ 100 mil) e demais serviços e compras (até R$ 50 mil), desde que não sejam parcelas de um mesmo objeto; licitação deserta; preços manifestamente superiores aos de mercado; emergência ou calamidade. Os limites em reais podem ser atualizados pelo Conselho de Administração (confira o §3º do art. 29).</li><li><b>Inexigibilidade (art. 30)</b>: inviabilidade de competição, em especial fornecedor exclusivo, profissional do setor artístico consagrado e serviços técnicos especializados de natureza singular com profissional de notória especialização.</li><li>Se houver sobrepreço ou superfaturamento comprovado, respondem solidariamente quem decidiu pela contratação direta e o contratado (art. 30, §2º).</li></ul>","Lei 13.303/2016, arts. 29 e 30 (confira os incisos)."],
["3. Princípios e diretrizes (arts. 31 e 32)","<p>A licitação busca a proposta mais vantajosa, inclusive quanto ao <b>ciclo de vida do objeto</b>, e evita sobrepreço e superfaturamento. Princípios: impessoalidade, moralidade, igualdade, publicidade, eficiência, probidade administrativa, economicidade, desenvolvimento nacional sustentável, vinculação ao instrumento convocatório, obtenção de competitividade e julgamento objetivo. Diretrizes do art. 32: padronização, busca da maior vantagem competitiva, <b>parcelamento</b> do objeto (sem perder economia de escala), <b>preferência pelo pregão</b> para bens e serviços comuns e observância da política de integridade.</p>","Lei 13.303/2016, arts. 31 e 32."],
["4. Orçamento, impedimentos e regulamento (arts. 34 a 41)","<ul><li>O valor estimado é, em regra, <b>sigiloso</b>, podendo a empresa justificar a publicidade; no julgamento por maior desconto, o preço estimado consta do edital (art. 34).</li><li>Impedimentos (art. 38), entre outros: empresa cujo administrador ou sócio com mais de 5% do capital seja diretor ou empregado da contratante; empresa suspensa pela contratante; empresa declarada inidônea.</li><li>Prazos mínimos entre o edital e as propostas (art. 39): bens, 5 dias úteis (menor preço ou maior desconto) ou 10 (demais critérios); obras e serviços, 15 dias úteis (menor preço ou maior desconto) ou 30 (demais).</li><li>Cada empresa edita seu <b>regulamento interno de licitações e contratos</b> (art. 40).</li><li>Qualquer cidadão pode impugnar o edital até 5 dias úteis antes da abertura (art. 41).</li></ul>","Lei 13.303/2016, arts. 34, 38, 39, 40 e 41."],
["5. Regimes de execução e critérios de julgamento (arts. 42 a 54)","<ul><li><b>Regimes</b> para obras e serviços de engenharia: empreitada por preço unitário, por preço global, tarefa, empreitada integral, <b>contratação semi-integrada</b> (projeto executivo, execução e demais operações) e <b>contratação integrada</b> (projetos básico e executivo, execução e demais operações). A <b>matriz de riscos</b> é definida nos arts. 42 e 43.</li><li><b>Critérios de julgamento</b> (art. 54): menor preço; maior desconto; melhor combinação de técnica e preço; melhor técnica; melhor conteúdo artístico; maior oferta de preço; maior retorno econômico; melhor destinação de bens alienados.</li><li><b>Modos de disputa</b> (art. 52): aberto, fechado ou combinados.</li><li><b>Empate</b> (art. 55), na ordem: disputa final; avaliação de desempenho contratual prévio; critérios de tecnologia e ME/EPP previstos em lei; sorteio.</li></ul>","Lei 13.303/2016, arts. 42, 43, 52, 54 e 55."],
["6. Fases da licitação (art. 51) e procedimentos auxiliares (art. 63)","<p>Ordem legal das fases: (I) <b>preparação</b>; (II) divulgação; (III) apresentação de lances ou propostas; (IV) <b>julgamento</b>; (V) verificação de efetividade; (VI) <b>negociação</b>; (VII) <b>habilitação</b>; (VIII) recursos; (IX) adjudicação; (X) homologação ou revogação. A habilitação vem <b>depois</b> do julgamento, podendo, excepcionalmente, ser antecipada por decisão motivada (inversão de fases). Como regra, há fase recursal única.</p><p><b>Procedimentos auxiliares</b> (art. 63): pré-qualificação permanente, cadastramento, sistema de registro de preços e catálogo eletrônico de padronização.</p>","Lei 13.303/2016, arts. 51 e 63."],
["7. Contratos (arts. 68 a 84)","<ul><li>Os contratos regem-se por suas cláusulas, pela Lei 13.303 e pelos <b>preceitos de direito privado</b> (art. 68).</li><li><b>Garantia</b> (art. 70): caução em dinheiro, seguro-garantia ou fiança bancária, à escolha do contratado; limite geral de 5% do valor do contrato, podendo chegar a 10% em contratações de grande vulto com complexidade técnica e riscos financeiros consideráveis.</li><li><b>Duração</b> (art. 71): em regra até 5 anos, com exceções (projetos previstos em plano de negócios e investimentos; casos em que o prazo maior é prática rotineira de mercado). Vedado prazo indeterminado.</li><li><b>Alteração</b>: por acordo entre as partes, vedada violação do dever de licitar (art. 72); acréscimos ou supressões unilaterais até <b>25%</b> do valor inicial atualizado, e até <b>50%</b> no caso de reforma de edifício ou equipamento (art. 81).</li><li><b>Sanções</b> (art. 83): advertência; multa; suspensão temporária de participação em licitação e impedimento de contratar com a entidade sancionadora por prazo não superior a 2 anos.</li></ul>","Lei 13.303/2016, arts. 68, 70, 71, 72, 81 e 83."],
["8. Fiscalização e controle (arts. 85 a 91)","<p>As estatais sujeitam-se à fiscalização do Estado e da sociedade: controle interno, controle externo pelo Tribunal de Contas (art. 87), publicidade de informações e canais de denúncia, além de deveres de governança. O art. 91 trata da adaptação de empresas já existentes à lei. Leia os arts. 85 a 91 na íntegra.</p>","Lei 13.303/2016, arts. 85 a 91."],
["9. LC 123/2006, arts. 42 a 49 (ME e EPP)","<ul><li><b>Regularidade fiscal e trabalhista</b> só é exigida na <b>assinatura do contrato</b> (art. 42). Havendo restrição, prazo de 5 dias úteis, prorrogável por igual período, após ser declarado vencedor (art. 43); a não regularização gera decadência do direito à contratação.</li><li><b>Empate ficto</b> (art. 44): propostas de ME/EPP iguais ou até 10% superiores à melhor proposta; no pregão, até 5%. A ME/EPP mais bem classificada pode apresentar proposta inferior e vencer.</li><li><b>Tratamento diferenciado</b> (arts. 47 e 48): licitação <b>exclusiva</b> para ME/EPP em itens de até R$ 80 mil; exigência de <b>subcontratação</b> em obras e serviços; <b>cota de até 25%</b> do objeto para bens divisíveis; possibilidade de prioridade para empresas sediadas local ou regionalmente, até 10% do melhor preço.</li><li>Não se aplica (art. 49), por exemplo, quando não houver ao menos 3 fornecedores competitivos ME/EPP sediados local ou regionalmente, ou quando o tratamento for desvantajoso para a Administração.</li><li>A LC 147/2014 tornou o tratamento diferenciado obrigatório (\"deverá\") e alterou dispositivos da LC 123.</li></ul>","LC 123/2006, arts. 42 a 49; LC 147/2014."]
],
mapa:`CONTRATAÇÃO (Lei 13.303/2016)
├── Art. 28: regra = licitar; §3º: comercialização do objeto social não segue o capítulo
├── Art. 29 dispensa | Art. 30 inexigibilidade
├── Arts. 31-32: princípios; parcelamento; pregão preferencial
├── Fases (art. 51): preparação → divulgação → lances → julgamento
│                    → negociação → HABILITAÇÃO → recursos → adjudicação → homologação
├── Critérios (art. 54): menor preço, maior desconto, técnica e preço...
├── Contratos: direito privado; garantia 5% (até 10%); prazo 5 anos;
│              alteração 25% (50% reforma); sanções até 2 anos (art. 83)
└── LC 123: regularidade só na assinatura; empate ficto 10% (5% pregão);
            exclusiva até R$ 80 mil; cota 25%`,
q:[
Q("Nos termos do art. 28, §3º, da Lei 13.303/2016, as empresas públicas e sociedades de economia mista são dispensadas da observância das regras de licitação do capítulo, entre outras hipóteses, na",["compra de qualquer bem, independentemente de valor.","comercialização, prestação ou execução, de forma direta, de produtos, serviços ou obras especificamente relacionados com seus objetos sociais.","contratação de serviços de limpeza de suas instalações.","contratação de obras de escritórios administrativos.","aquisição de material de escritório de grande valor."],1,["Compras em geral seguem a regra de licitar, salvo dispensa ou inexigibilidade.","É a hipótese do art. 28, §3º, I: atividade-fim, diretamente relacionada ao objeto social.","Serviços de limpeza são atividade-meio e seguem o regime de licitação.","Obras administrativas não são atividade-fim.","Compras de grande valor são licitadas."],"Lei 13.303/2016, art. 28, §3º."),
Q("Na sequência de fases prevista no art. 51 da Lei 13.303/2016, a habilitação ocorre, como regra,",["antes da apresentação de lances ou propostas.","depois do julgamento e da negociação, podendo ser antecipada excepcionalmente por decisão motivada.","somente após a homologação.","apenas em licitações de obras.","depois da adjudicação."],1,["É a regra da lei anterior; na Lei 13.303 a inversão de fases é a regra.","Na ordem legal, a habilitação vem após julgamento e negociação, com possibilidade de antecipação motivada.","A homologação é a última fase.","Aplica-se a qualquer objeto.","A adjudicação vem depois da habilitação e dos recursos."],"Lei 13.303/2016, art. 51 e §1º."),
Q("Quanto às garantias contratuais previstas na Lei 13.303/2016, é correto afirmar que",["a garantia é sempre obrigatória e de 30% do contrato.","o limite geral é de 5% do valor do contrato, podendo chegar a 10% em contratações de grande vulto com complexidade técnica e riscos financeiros consideráveis.","somente é aceita caução em dinheiro.","não pode ser exigida garantia em contratos de obras.","o limite é de 25% em qualquer contrato."],1,["A garantia pode ser exigida, mas não é de 30%.","Art. 70: limite geral de 5% e, nos casos de grande vulto com risco, até 10%.","A escolha da modalidade (caução, seguro-garantia ou fiança) é do contratado.","A garantia pode ser exigida em obras, serviços e compras.","25% é o limite de acréscimos unilaterais (art. 81), não da garantia."],"Lei 13.303/2016, art. 70."),
Q("Um contrato regido pela Lei 13.303/2016 que tem por objeto obra civil pode ter seu valor acrescido unilateralmente, nas mesmas condições contratuais, até o limite de",["10% do valor inicial atualizado.","25% do valor inicial atualizado.","50% para qualquer obra nova.","100% do valor inicial atualizado.","não há limite."],1,["Não é o percentual do art. 81.","Regra geral do art. 81: até 25%.","O limite de 50% aplica-se ao caso particular de reforma de edifício ou de equipamento, não a obra nova.","Excede os limites legais.","Há limites legais."],"Lei 13.303/2016, art. 81, §1º."),
Q("Segundo a LC 123/2006, em licitação na modalidade pregão, considera-se empate ficto quando a proposta de microempresa ou empresa de pequeno porte for",["igual ou até 5% superior à melhor proposta classificada.","igual ou até 10% superior à melhor proposta classificada.","até 20% superior à melhor proposta.","inferior à melhor proposta.","igual à melhor proposta, apenas."],0,["No pregão, o intervalo é de até 5% (art. 44, §2º).","10% é o intervalo geral para as demais modalidades, não o do pregão.","Não é o percentual legal.","Proposta inferior já seria a melhor.","O empate ficto abrange também propostas até o limite percentual superior."],"LC 123/2006, art. 44.")
]});
