MODS.push({n:6,t:"Tributos aplicáveis ao setor",edital:"IRPJ/CSLL, IRRF, ICMS, participações governamentais, PIS/PASEP, COFINS, CIDE, ISS, contribuição previdenciária, EC 132/2023, LC 214/2025",
alerta:"Alíquotas, limites e regimes mudam com frequência (especialmente na reforma tributária, em transição). <b>Não consegui consultar os textos oficiais</b>: confirme cada número na legislação vigente. O edital pede \"conhecimentos básicos\".",
intro:"O item de tributos do edital é amplo. O foco aqui é: qual tributo é de qual ente, o que tributa, o que é retenção na fonte e o que muda com a reforma (EC 132/2023 e LC 214/2025).",
obj:["Identificar competência, incidência e natureza de cada tributo listado.","Distinguir regime cumulativo e não cumulativo de PIS/COFINS.","Entender a CIDE-combustíveis e as participações governamentais do petróleo.","Compreender IRRF e retenções na contratação de serviços.","Conhecer a estrutura da reforma tributária: CBS, IBS e Imposto Seletivo."],
secs:[
["1. IRPJ e CSLL","<ul><li><b>IRPJ</b>: tributo federal sobre o lucro das pessoas jurídicas. Alíquota de 15%, mais <b>adicional de 10%</b> sobre a parcela do lucro que exceder R$ 20 mil por mês (R$ 240 mil por ano). Regimes: lucro real, presumido e arbitrado (Lei 9.249/1995).</li><li><b>CSLL</b>: contribuição social sobre o lucro líquido, com alíquota geral de 9% (Lei 7.689/1988), maior para instituições financeiras.</li></ul>","Lei 9.249/1995 (art. 3º); Lei 7.689/1988; RIR/2018 (Decreto 9.580)."],
["2. IRRF (Imposto de Renda Retido na Fonte)","<p>Mecanismo em que a fonte pagadora <b>retém e recolhe</b> o imposto de renda devido pelo beneficiário do rendimento (salários, serviços, aluguéis, juros, remessas ao exterior etc.). Funciona como <b>antecipação</b> do imposto devido ou como tributação definitiva, conforme o rendimento. Nos pagamentos de PJ a PJ por certos serviços, há retenção de IRRF e ainda das contribuições PIS, COFINS e CSLL (retenção conjunta de 4,65% sobre os pagamentos sujeitos à regra, Lei 10.833/2003, art. 30). Alíquotas de IRRF variam conforme a natureza do rendimento (consulte o RIR).</p>","RIR/2018; Lei 10.833/2003, art. 30."],
["3. PIS/PASEP e COFINS","<p>Contribuições federais sobre receita/faturamento. Regime <b>não cumulativo</b> (geral para lucro real): PIS 1,65% e COFINS 7,6%, com direito a crédito sobre insumos e despesas listadas (Leis 10.637/2002 e 10.833/2003). Regime <b>cumulativo</b>: PIS 0,65% e COFINS 3% (Lei 9.718/1998), sem créditos. Combustíveis têm regime especial (incidência concentrada/monofásica) definido em lei.</p>","Leis 10.637/2002, 10.833/2003 e 9.718/1998."],
["4. ICMS","<p>Imposto <b>estadual e distrital</b> sobre operações relativas à circulação de mercadorias e serviços de transporte interestadual e intermunicipal e de comunicação (CF, art. 155, II; LC 87/1996). É <b>não cumulativo</b>. Sobre operações com energia elétrica, telecomunicações, derivados de petróleo, combustíveis e minerais, nenhum outro imposto pode incidir além de ICMS, imposto de importação e imposto de exportação (CF, art. 155, §3º). A tributação monofásica de combustíveis foi introduzida pela LC 192/2022 (confira o regramento vigente).</p>","CF, art. 155; LC 87/1996; LC 192/2022."],
["5. ISS","<p>Imposto <b>municipal e distrital</b> sobre serviços da lista da LC 116/2003, com alíquotas entre 2% e 5% (alíquota mínima e máxima definidas em lei complementar). Em regra, é devido no local do estabelecimento do prestador, com exceções previstas na lei (por exemplo, construção civil, no local da obra).</p>","LC 116/2003; CF, art. 156, III."],
["6. Contribuição previdenciária","<p>Contribuição patronal de <b>20% sobre a folha</b> (Lei 8.212/1991, art. 22, I), acrescida do RAT (1%, 2% ou 3%, conforme o risco) e de contribuições a terceiros. Na contratação de serviços mediante <b>cessão de mão de obra</b> ou empreitada, a contratante retém <b>11%</b> do valor da nota e recolhe em nome do prestador (art. 31). Confira as regras de desoneração vigentes.</p>","Lei 8.212/1991, arts. 22 e 31."],
["7. CIDE-combustíveis (Leis 10.336/2001 e 10.636/2002)","<p>Contribuição de Intervenção no Domínio Econômico incidente sobre a <b>importação e a comercialização no mercado interno</b> de gasolina, diesel, querosene de aviação e outros querosenes, óleos combustíveis, GLP e álcool etílico combustível. Contribuintes: produtor, formulador e importador. Alíquotas são fixadas em reais por unidade de medida (m³ ou tonelada) e podem ser reduzidas por ato do Poder Executivo. A Lei 10.636/2002 trata da aplicação dos recursos arrecadados (subsídios, projetos ambientais e infraestrutura de transportes, conforme a CF, art. 177, §4º).</p>","Lei 10.336/2001; Lei 10.636/2002; CF, art. 177, §4º."],
["8. Participações governamentais","<p>Previstas na Lei 9.478/1997, art. 45: <b>bônus de assinatura</b>, <b>royalties</b>, <b>participação especial</b> (sobre campos de grande produção ou rentabilidade) e <b>pagamento pela ocupação ou retenção de área</b>. Os royalties são a compensação financeira pela exploração, calculados sobre a produção (a lei fixa 10% como alíquota básica, reduzível em certas condições). Não são tributos em sentido estrito, mas receitas patrimoniais.</p>","Lei 9.478/1997, arts. 45 a 52."],
["9. Reforma tributária: EC 132/2023 e LC 214/2025","<p>A EC 132/2023 criou o <b>IBS</b> (imposto sobre bens e serviços, de competência de estados e municípios), a <b>CBS</b> (contribuição sobre bens e serviços, federal) e o <b>Imposto Seletivo</b> (sobre bens e serviços prejudiciais à saúde ou ao meio ambiente). O IBS substitui ICMS e ISS; a CBS substitui PIS e COFINS (e o IPI é reduzido). A LC 214/2025 regulamenta IBS, CBS e Imposto Seletivo. A transição é gradual (a partir de 2026, com fase de teste, e substituição progressiva até 2033). Princípios: não cumulatividade ampla, cobrança no destino e neutralidade.</p>","EC 132/2023; LC 214/2025 (confira o cronograma de transição)."]
],
mapa:`TRIBUTOS
├── Federais: IRPJ (15% + 10% adicional > R$ 20 mil/mês), CSLL (9%),
│             PIS/COFINS (não cumulativo 1,65% / 7,6%), CIDE, IRRF
├── Estadual: ICMS | Municipal: ISS (2% a 5%)
├── Previdência: 20% patronal + RAT; retenção de 11% (cessão de mão de obra)
├── CIDE-combustíveis: importação e comercialização (Lei 10.336)
├── Participações governamentais (art. 45, Lei 9.478):
│   bônus de assinatura, royalties, participação especial, ocupação de área
└── Reforma: CBS (federal) ← PIS/COFINS; IBS (estados/municípios) ← ICMS/ISS;
    Imposto Seletivo; transição até 2033`,
q:[
Q("Nos termos usuais da legislação do IRPJ, incide adicional de 10% sobre a parcela do lucro que exceder, por mês,",["R$ 2.000,00.","R$ 20.000,00.","R$ 200.000,00.","R$ 2.000.000,00.","não há adicional."],1,["Valor abaixo do limite legal.","O adicional incide sobre a parcela do lucro que exceder R$ 20 mil por mês (R$ 240 mil por ano).","Valor acima do limite legal.","Valor acima do limite legal.","Existe adicional de 10%."],"Lei 9.249/1995, art. 3º."),
Q("No regime não cumulativo, as alíquotas gerais de PIS/PASEP e COFINS são, respectivamente,",["0,65% e 3%.","1,65% e 7,6%.","9% e 15%.","2% e 5%.","7,6% e 1,65%."],1,["São as alíquotas do regime cumulativo.","São as alíquotas do regime não cumulativo (Leis 10.637/2002 e 10.833/2003).","Referem-se a CSLL e à alíquota-base do IRPJ.","2% a 5% é a faixa do ISS.","Inverte as alíquotas."],"Leis 10.637/2002 e 10.833/2003."),
Q("A CIDE-combustíveis, instituída pela Lei 10.336/2001, incide sobre",["a folha de pagamento das distribuidoras.","a importação e a comercialização no mercado interno de combustíveis como gasolina, diesel e GLP, tendo como contribuintes o produtor, o formulador e o importador.","o lucro líquido das refinarias.","a exportação de petróleo bruto.","a prestação de serviços de transporte municipal."],1,["Trata-se da contribuição previdenciária.","Essa é a incidência da CIDE-combustíveis.","Isso é a CSLL.","A CIDE-combustíveis alcança importação e comercialização interna de combustíveis, não exportação de petróleo bruto.","Trata-se de ISS."],"Lei 10.336/2001."),
Q("De acordo com a Lei 9.478/1997, NÃO integra o rol de participações governamentais",["bônus de assinatura.","royalties.","participação especial.","pagamento pela ocupação ou retenção de área.","imposto de importação."],4,["Integra o rol (art. 45).","Integra o rol.","Integra o rol.","Integra o rol.","O imposto de importação é tributo federal, sem relação com as participações do art. 45."],"Lei 9.478/1997, art. 45."),
Q("Após a regulamentação da reforma tributária (EC 132/2023 e LC 214/2025), a CBS e o IBS passam a substituir, respectivamente,",["ISS e ICMS.","PIS/COFINS e ICMS/ISS.","IRPJ e CSLL.","IPVA e IPTU.","CIDE e royalties."],1,["Inverte a lógica: ISS e ICMS serão substituídos pelo IBS, em conjunto.","A CBS (federal) substitui PIS e COFINS; o IBS substitui ICMS e ISS.","Tributos sobre a renda não são substituídos.","Impostos patrimoniais não são substituídos.","Não são substituídos por CBS/IBS."],"EC 132/2023; LC 214/2025.")
]});
