MODS.push({n:6,t:"Tributos aplicáveis ao setor",edital:"IRPJ/CSLL, IRRF, ICMS, participações governamentais, PIS/PASEP, COFINS, CIDE, ISS, contribuição previdenciária, EC 132/2023, LC 214/2025",
alerta:"Alíquotas, limites e regimes mudam com frequência (especialmente na reforma tributária, em transição). A CIDE (Leis 10.336/2001 e 10.636/2002) foi conferida nos textos enviados. <b>O restante (IRPJ, PIS/COFINS, ICMS, ISS, previdência, reforma tributária) vem de conhecimento prévio</b>: confirme cada número na legislação vigente. O edital pede \"conhecimentos básicos\".",
intro:"O item de tributos do edital é amplo. O foco aqui é: qual tributo é de qual ente, o que tributa, o que é retenção na fonte e o que muda com a reforma (EC 132/2023 e LC 214/2025).",
obj:["Identificar competência, incidência e natureza de cada tributo listado.","Distinguir regime cumulativo e não cumulativo de PIS/COFINS.","Entender a CIDE-combustíveis e as participações governamentais do petróleo.","Compreender IRRF e retenções na contratação de serviços.","Conhecer a estrutura da reforma tributária: CBS, IBS e Imposto Seletivo."],
secs:[
["1. IRPJ e CSLL","<ul><li><b>IRPJ</b>: tributo federal sobre o lucro das pessoas jurídicas. Alíquota de 15%, mais <b>adicional de 10%</b> sobre a parcela do lucro que exceder R$ 20 mil por mês (R$ 240 mil por ano). Regimes: lucro real, presumido e arbitrado (Lei 9.249/1995).</li><li><b>CSLL</b>: contribuição social sobre o lucro líquido, com alíquota geral de 9% (Lei 7.689/1988), maior para instituições financeiras.</li></ul>","Lei 9.249/1995 (art. 3º); Lei 7.689/1988; RIR/2018 (Decreto 9.580)."],
["2. IRRF (Imposto de Renda Retido na Fonte)","<p>Mecanismo em que a fonte pagadora <b>retém e recolhe</b> o imposto de renda devido pelo beneficiário do rendimento (salários, serviços, aluguéis, juros, remessas ao exterior etc.). Funciona como <b>antecipação</b> do imposto devido ou como tributação definitiva, conforme o rendimento. Nos pagamentos de PJ a PJ por certos serviços, há retenção de IRRF e ainda das contribuições PIS, COFINS e CSLL (retenção conjunta de 4,65% sobre os pagamentos sujeitos à regra, Lei 10.833/2003, art. 30). Alíquotas de IRRF variam conforme a natureza do rendimento (consulte o RIR).</p>","RIR/2018; Lei 10.833/2003, art. 30."],
["3. PIS/PASEP e COFINS","<p>Contribuições federais sobre receita/faturamento. Regime <b>não cumulativo</b> (geral para lucro real): PIS 1,65% e COFINS 7,6%, com direito a crédito sobre insumos e despesas listadas (Leis 10.637/2002 e 10.833/2003). Regime <b>cumulativo</b>: PIS 0,65% e COFINS 3% (Lei 9.718/1998), sem créditos. Combustíveis têm regime especial (incidência concentrada/monofásica) definido em lei.</p>","Leis 10.637/2002, 10.833/2003 e 9.718/1998."],
["4. ICMS","<p>Imposto <b>estadual e distrital</b> sobre operações relativas à circulação de mercadorias e serviços de transporte interestadual e intermunicipal e de comunicação (CF, art. 155, II; LC 87/1996). É <b>não cumulativo</b>. Sobre operações com energia elétrica, telecomunicações, derivados de petróleo, combustíveis e minerais, nenhum outro imposto pode incidir além de ICMS, imposto de importação e imposto de exportação (CF, art. 155, §3º). A tributação monofásica de combustíveis foi introduzida pela LC 192/2022 (confira o regramento vigente).</p>","CF, art. 155; LC 87/1996; LC 192/2022."],
["5. ISS","<p>Imposto <b>municipal e distrital</b> sobre serviços da lista da LC 116/2003, com alíquotas entre 2% e 5% (alíquota mínima e máxima definidas em lei complementar). Em regra, é devido no local do estabelecimento do prestador, com exceções previstas na lei (por exemplo, construção civil, no local da obra).</p>","LC 116/2003; CF, art. 156, III."],
["6. Contribuição previdenciária","<p>Contribuição patronal de <b>20% sobre a folha</b> (Lei 8.212/1991, art. 22, I), acrescida do RAT (1%, 2% ou 3%, conforme o risco) e de contribuições a terceiros. Na contratação de serviços mediante <b>cessão de mão de obra</b> ou empreitada, a contratante retém <b>11%</b> do valor da nota e recolhe em nome do prestador (art. 31). Confira as regras de desoneração vigentes.</p>","Lei 8.212/1991, arts. 22 e 31."],
["7. CIDE-combustíveis (Lei 10.336/2001)","<ul><li><b>Instituição</b>: Cide incidente sobre a importação e a comercialização de petróleo e derivados, gás natural e derivados e álcool etílico combustível (art. 1º; CF, arts. 149 e 177).</li><li><b>Contribuintes</b> (art. 2º): o <b>produtor</b>, o <b>formulador</b> e o <b>importador</b>, pessoa física ou jurídica, dos combustíveis líquidos listados.</li><li><b>Fatos geradores</b> (art. 3º): operações de <b>importação</b> e de <b>comercialização no mercado interno</b> de gasolinas e suas correntes; diesel e suas correntes; querosene de aviação e outros querosenes; óleos combustíveis (fuel-oil); GLP, inclusive o derivado de gás natural e de nafta; álcool etílico combustível. <b>Não incide</b> sobre receitas de exportação (§2º).</li><li><b>Base de cálculo</b>: a unidade de medida (m³ ou tonelada) adotada na lei (art. 4º), com <b>alíquotas específicas</b> em reais por unidade. Valores fixados no art. 5º (redação da Lei 10.636/2002): gasolina R$ 860,00/m³; diesel R$ 390,00/m³; querosene de aviação e outros querosenes R$ 92,10/m³; óleos combustíveis R$ 40,90/t; GLP R$ 250,00/t; álcool etílico combustível R$ 37,20/m³. O Poder Executivo pode <b>reduzir e restabelecer</b> as alíquotas até o valor do art. 5º (art. 9º), portanto esses valores são o teto legal, e não necessariamente o valor cobrado hoje.</li><li><b>Pagamento</b> (art. 6º): na importação, na data do registro da Declaração de Importação; na comercialização, apuração mensal e pagamento até o último dia útil da primeira quinzena do mês seguinte.</li><li><b>Deduções</b>: da Cide devida na comercialização pode-se deduzir a paga na importação ou embutida na aquisição de outro contribuinte (art. 7º); a Cide também pode ser deduzida de PIS/Pasep e Cofins, até limites por produto (art. 8º).</li><li><b>Isenção</b> (art. 10): venda a empresa comercial exportadora com fim específico de exportação; se não exportar em <b>180 dias</b>, paga a Cide.</li><li><b>Administração e fiscalização</b>: Secretaria da Receita Federal (art. 13).</li><li><b>Destinação</b> (art. 1º, §1º): (I) subsídios a preços ou transporte de álcool combustível, gás natural e derivados e derivados de petróleo; (II) projetos ambientais da indústria do petróleo e do gás; (III) programas de infraestrutura de transportes; (IV) auxílio para mitigar o efeito do preço do GLP no orçamento de famílias de baixa renda. A União repassa aos Estados e ao DF a parcela do art. 159, III, da CF, para infraestrutura de transportes, com critérios de 40% (malha viária), 30% (consumo dos combustíveis), 20% (população) e 10% (partes iguais) (art. 1º-A); 25% do valor de cada Estado vai aos Municípios (art. 1º-B).</li></ul><p>A versão consultada indica remissões a alterações recentes (Lei 15.432/2026 e LC 214/2025): confirme a redação vigente.</p>","Lei 10.336/2001 (texto atualizado, conferido no arquivo enviado)."],
["7-B. Aplicação dos recursos da Cide (Lei 10.636/2002)","<ul><li>Fixa critérios e diretrizes para aplicação da arrecadação da Cide e cria o <b>FNIT</b> (Fundo Nacional de Infraestrutura de Transportes) (art. 1º).</li><li><b>Projetos ambientais</b> da indústria do petróleo e do gás, administrados pelo <b>Ministério do Meio Ambiente</b>: monitoramento e fiscalização de atividades poluidoras, planos de contingência, estudos e educação ambiental, apoio a unidades de conservação, recuperação de áreas degradadas, gestão de florestas e recursos genéticos e produção de biocombustíveis (art. 4º).</li><li><b>Infraestrutura de transportes</b>: objetivos essenciais incluem a redução do consumo de combustíveis automotivos, o atendimento mais econômico da demanda de transporte, a segurança e o conforto dos usuários e a menor participação de fretes e custos portuários na formação dos preços (art. 6º).</li><li>É <b>vedada</b> a aplicação de recursos da Cide em investimentos de responsabilidade dos concessionários (arts. 4º, §1º, e 8º).</li><li><b>FNIT</b> (art. 10): vinculado ao Ministério dos Transportes, <b>fundo contábil de natureza financeira</b>, destinado a financiar programas de investimento em infraestrutura de transportes; aplicação <b>multimodal</b> (art. 11, §1º).</li></ul>","Lei 10.636/2002 (texto atualizado, conferido no arquivo enviado)."],
["8. Participações governamentais","<p>Previstas na Lei 9.478/1997, art. 45: <b>bônus de assinatura</b>, <b>royalties</b>, <b>participação especial</b> (sobre campos de grande produção ou rentabilidade) e <b>pagamento pela ocupação ou retenção de área</b>. Os royalties são a compensação financeira pela exploração, calculados sobre a produção (a lei fixa 10% como alíquota básica, reduzível em certas condições). Não são tributos em sentido estrito, mas receitas patrimoniais.</p>","Lei 9.478/1997, arts. 45 a 52."],
["9. Reforma tributária: EC 132/2023 e LC 214/2025","<p>A EC 132/2023 criou o <b>IBS</b> (imposto sobre bens e serviços, de competência de estados e municípios), a <b>CBS</b> (contribuição sobre bens e serviços, federal) e o <b>Imposto Seletivo</b> (sobre bens e serviços prejudiciais à saúde ou ao meio ambiente). O IBS substitui ICMS e ISS; a CBS substitui PIS e COFINS (e o IPI é reduzido). A LC 214/2025 regulamenta IBS, CBS e Imposto Seletivo. A transição é gradual (a partir de 2026, com fase de teste, e substituição progressiva até 2033). Princípios: não cumulatividade ampla, cobrança no destino e neutralidade.</p>","EC 132/2023; LC 214/2025 (confira o cronograma de transição)."]
],
mapa:`TRIBUTOS
├── Federais: IRPJ (15% + 10% adicional > R$ 20 mil/mês), CSLL (9%),
│             PIS/COFINS (não cumulativo 1,65% / 7,6%), CIDE, IRRF
├── Estadual: ICMS | Municipal: ISS (2% a 5%)
├── Previdência: 20% patronal + RAT; retenção de 11% (cessão de mão de obra)
├── CIDE-combustíveis: importação e comercialização (Lei 10.336)
├── Participações governamentais (art. 45, Lei 9.478):
│   bônus de assinatura, royalties, participação especial, ocupação de área
└── Reforma: CBS (federal) ← PIS/COFINS; IBS (estados/municípios) ← ICMS/ISS;
    Imposto Seletivo; transição até 2033`,
q:[
Q("Nos termos usuais da legislação do IRPJ, incide adicional de 10% sobre a parcela do lucro que exceder, por mês,",["R$ 2.000,00.","R$ 20.000,00.","R$ 200.000,00.","R$ 2.000.000,00.","não há adicional."],1,["Valor abaixo do limite legal.","O adicional incide sobre a parcela do lucro que exceder R$ 20 mil por mês (R$ 240 mil por ano).","Valor acima do limite legal.","Valor acima do limite legal.","Existe adicional de 10%."],"Lei 9.249/1995, art. 3º."),
Q("No regime não cumulativo, as alíquotas gerais de PIS/PASEP e COFINS são, respectivamente,",["0,65% e 3%.","1,65% e 7,6%.","9% e 15%.","2% e 5%.","7,6% e 1,65%."],1,["São as alíquotas do regime cumulativo.","São as alíquotas do regime não cumulativo (Leis 10.637/2002 e 10.833/2003).","Referem-se a CSLL e à alíquota-base do IRPJ.","2% a 5% é a faixa do ISS.","Inverte as alíquotas."],"Leis 10.637/2002 e 10.833/2003."),
Q("A CIDE-combustíveis, instituída pela Lei 10.336/2001, tem como contribuintes",["apenas os postos revendedores.","o produtor, o formulador e o importador dos combustíveis líquidos listados na lei.","o consumidor final.","apenas a Petrobras.","apenas o distribuidor de GLP."],1,["A revenda a varejo não é o contribuinte legal.","Art. 2º: produtor, formulador e importador.","O consumidor final não é contribuinte legal.","Qualquer produtor, formulador ou importador é contribuinte, não só a Petrobras.","O distribuidor não é o contribuinte definido no art. 2º."],"Lei 10.336/2001, art. 2º."),
Q("Segundo a Lei 10.336/2001, a Cide-combustíveis",["incide também sobre as receitas de exportação de petróleo bruto.","tem como fatos geradores a importação e a comercialização no mercado interno de gasolinas, diesel, querosenes, óleos combustíveis, GLP e álcool etílico combustível, e não incide sobre receitas de exportação.","incide sobre a folha de salários do setor.","é administrada pela ANP.","tem alíquota ad valorem única de 10%."],1,["O art. 3º, §2º afasta a incidência sobre receitas de exportação.","Art. 3º, caput e §2º.","Não incide sobre folha.","A administração e a fiscalização são da Secretaria da Receita Federal (art. 13).","As alíquotas são específicas, em reais por m³ ou tonelada (art. 5º)."],"Lei 10.336/2001, arts. 3º, 5º e 13."),
Q("A Lei 10.636/2002, que trata da aplicação dos recursos da Cide, criou o",["Fundo Social do pré-sal.","Fundo Nacional de Infraestrutura de Transportes (FNIT), vinculado ao Ministério dos Transportes.","Fundo de Garantia do Tempo de Serviço.","Fundo Nacional do Petróleo, vinculado à ANP.","Fundo Soberano do Brasil."],1,["O Fundo Social é citado na Lei 9.478 (art. 50), não na 10.636.","Art. 10: FNIT, fundo contábil de natureza financeira.","Não é fundo criado por essa lei.","Não existe esse fundo na lei.","Não é fundo criado por essa lei."],"Lei 10.636/2002, art. 10."),
Q("De acordo com a Lei 9.478/1997, NÃO integra o rol de participações governamentais",["bônus de assinatura.","royalties.","participação especial.","pagamento pela ocupação ou retenção de área.","imposto de importação."],4,["Integra o rol (art. 45).","Integra o rol.","Integra o rol.","Integra o rol.","O imposto de importação é tributo federal, sem relação com as participações do art. 45."],"Lei 9.478/1997, art. 45."),
Q("Após a regulamentação da reforma tributária (EC 132/2023 e LC 214/2025), a CBS e o IBS passam a substituir, respectivamente,",["ISS e ICMS.","PIS/COFINS e ICMS/ISS.","IRPJ e CSLL.","IPVA e IPTU.","CIDE e royalties."],1,["Inverte a lógica: ISS e ICMS serão substituídos pelo IBS, em conjunto.","A CBS (federal) substitui PIS e COFINS; o IBS substitui ICMS e ISS.","Tributos sobre a renda não são substituídos.","Impostos patrimoniais não são substituídos.","Não são substituídos por CBS/IBS."],"EC 132/2023; LC 214/2025.")
]});
