MODS.push({n:7,t:"Matemática financeira e avaliação econômica (VPL e TIR)",edital:"Matemática financeira; métodos de avaliação econômica; VPL e TIR",
intro:"Base para análise de investimentos, contratos e financiamentos. As questões costumam pedir cálculo direto de juros compostos, taxas equivalentes, valor presente líquido e interpretação da TIR.",
obj:["Aplicar juros simples e compostos.","Converter taxas (equivalentes, nominal, efetiva e real).","Calcular séries uniformes e comparar SAC e Price.","Calcular e interpretar VPL e TIR, e o payback."],
secs:[
["1. Juros simples e compostos","<ul><li>Simples: <code>J = C·i·n</code>; <code>M = C(1 + i·n)</code>.</li><li>Compostos: <code>M = C(1 + i)ⁿ</code>. Desconto composto: <code>C = M/(1 + i)ⁿ</code>.</li><li>Taxas <b>equivalentes</b> (compostas): <code>(1 + i_a) = (1 + i_m)¹²</code>. Taxas <b>proporcionais</b> (juros simples) dividem a taxa pelo número de períodos.</li><li>Taxa <b>nominal</b> (capitalização diferente do período da taxa) × <b>efetiva</b>.</li><li>Taxa <b>real</b>: <code>(1 + r) = (1 + i)/(1 + π)</code>, com π a inflação.</li></ul>","ASSAF NETO, A. <i>Matemática Financeira e suas Aplicações</i>, Atlas."],
["2. Séries uniformes e amortização","<ul><li>Valor presente de série postecipada: <code>PV = PMT · [1 − (1 + i)⁻ⁿ]/i</code>. Valor futuro: <code>FV = PMT · [(1 + i)ⁿ − 1]/i</code>. Perpetuidade: <code>PV = PMT/i</code>.</li><li><b>SAC</b>: amortização constante; juros e prestações <b>decrescentes</b>.</li><li><b>Price (tabela Price)</b>: prestações constantes; amortização <b>crescente</b>, juros decrescentes.</li></ul>","ASSAF NETO."],
["3. Avaliação de investimentos","<ul><li><b>VPL</b> = Σ FCₜ/(1 + k)ᵗ − I₀, com k = taxa mínima de atratividade (TMA/custo de capital). VPL &gt; 0: projeto cria valor (aceitar).</li><li><b>TIR</b>: taxa que <b>zera o VPL</b>. Regra: aceitar se TIR &gt; TMA.</li><li><b>Payback</b> simples: tempo para recuperar o investimento (ignora o valor do dinheiro no tempo e o fluxo após a recuperação); descontado usa fluxos trazidos a valor presente.</li><li>Fluxos com várias inversões de sinal podem ter mais de uma TIR; para projetos mutuamente exclusivos o VPL é o critério preferível.</li></ul>","BREALEY, R.; MYERS, S.; ALLEN, F. <i>Princípios de Finanças Corporativas</i>, AMGH; GITMAN, L. <i>Princípios de Administração Financeira</i>."]
],
mapa:`MATEMÁTICA FINANCEIRA
├── Simples: M = C(1 + in)   Compostos: M = C(1 + i)^n
├── Taxas: equivalente (compostas) × proporcional (simples); real = (1+i)/(1+π) − 1
├── Séries: PV = PMT[1 − (1+i)^-n]/i;  SAC × Price
└── Projetos: VPL > 0 aceita | TIR = taxa que zera VPL | aceita se TIR > TMA | payback`,
q:[
Q("O montante obtido pela aplicação de R$ 1.000,00 a juros compostos de 10% ao ano, por 2 anos, é de",["R$ 1.100,00.","R$ 1.200,00.","R$ 1.210,00.","R$ 1.220,00.","R$ 1.331,00."],2,["Um ano de juros apenas.","Seria o montante a juros simples em 2 anos.","M = 1000 · 1,1² = 1210.","Erro de cálculo.","Corresponde a 3 anos."],"Assaf Neto."),
Q("A taxa anual equivalente, em juros compostos, a uma taxa de 1% ao mês é de aproximadamente",["12,00%.","12,68%.","13,00%.","11,50%.","10,00%."],1,["Seria a taxa proporcional (juros simples), não a equivalente.","1,01¹² − 1 ≈ 0,1268.","Sem base no cálculo.","Sem base no cálculo.","Sem base no cálculo."],"Assaf Neto."),
Q("Um projeto exige investimento inicial de R$ 1.000,00 e retorna R$ 600,00 ao final de cada um dos dois anos seguintes. Adotando taxa mínima de atratividade de 10% ao ano, o VPL é de aproximadamente",["R$ 200,00.","R$ 41,30.","−R$ 41,30.","R$ 100,00.","zero."],1,["Soma fluxos sem descontar (1200 − 1000).","VPL = 600/1,1 + 600/1,21 − 1000 ≈ 545,45 + 495,87 − 1000 ≈ 41,3.","Sinal invertido.","Sem base no cálculo.","VPL zero ocorreria se a TIR fosse exatamente 10%."],"Brealey; Myers; Allen."),
Q("Um investimento de R$ 100,00 gera um único retorno de R$ 121,00 ao final do segundo ano. A taxa interna de retorno (TIR) é de",["10% ao ano.","21% ao ano.","11% ao ano.","5% ao ano.","20% ao ano."],0,["100·(1 + i)² = 121, então 1 + i = 1,1 e i = 10%.","21% é o ganho total no período, não a taxa anual.","Sem base no cálculo.","Sem base no cálculo.","Sem base no cálculo."],"Definição de TIR (Brealey; Myers; Allen)."),
Q("Sobre os sistemas de amortização, é correto afirmar que",["no SAC as prestações são constantes e a amortização cresce.","na tabela Price as prestações são constantes e a parcela de juros decresce ao longo do tempo.","no SAC a amortização é decrescente.","na tabela Price a amortização é constante.","em ambos os sistemas a parcela de juros é constante."],1,["No SAC a amortização é constante e as prestações decrescem.","Na Price a prestação é constante; a amortização cresce e os juros decrescem.","No SAC a amortização é constante.","Na Price a amortização é crescente.","A parcela de juros decresce nos dois, pois incide sobre saldo devedor decrescente."],"Assaf Neto.")
]});
