MODS.push({n:8,t:"Noções de micro e macroeconomia",edital:"Noções elementares de micro e macroeconomia",
intro:"Conceitos básicos: formação de preços, elasticidades, estruturas de mercado e indicadores e políticas macroeconômicas. Úteis para entender a comercialização de combustíveis e o ambiente de negócios.",
obj:["Analisar oferta, demanda e equilíbrio.","Calcular e interpretar elasticidades.","Distinguir estruturas de mercado.","Explicar PIB, inflação, política monetária e fiscal, câmbio e balanço de pagamentos."],
secs:[
["1. Demanda, oferta e equilíbrio","<ul><li>Lei da demanda: preço sobe, quantidade demandada cai (<i>ceteris paribus</i>). Lei da oferta: preço sobe, quantidade ofertada sobe.</li><li>Variação do <b>preço do próprio bem</b> = movimento <b>ao longo</b> da curva. Variação de renda, preços de outros bens, preferências ou expectativas = <b>deslocamento</b> da curva.</li><li>Bens normais (demanda sobe com a renda) e inferiores; <b>substitutos</b> (preço de um sobe, demanda do outro sobe) e <b>complementares</b>.</li><li>Equilíbrio: preço em que quantidade demandada = ofertada.</li></ul>","MANKIW, N. G. <i>Introdução à Economia</i>; VASCONCELLOS, M. A. S. <i>Economia: Micro e Macro</i>, Atlas."],
["2. Elasticidades","<ul><li><b>Elasticidade-preço da demanda</b>: E = %ΔQ / %ΔP. |E| &gt; 1: elástica; |E| &lt; 1: inelástica; |E| = 1: unitária.</li><li>Demanda <b>inelástica</b>: aumento de preço <b>eleva</b> a receita total. Demanda <b>elástica</b>: aumento de preço reduz a receita.</li><li>Elasticidade-renda e elasticidade cruzada (positiva entre substitutos, negativa entre complementares).</li></ul>","MANKIW; PINDYCK, R.; RUBINFELD, D. <i>Microeconomia</i>."],
["3. Estruturas de mercado e custos","<ul><li>Concorrência perfeita (muitos agentes, preço dado); monopólio (um vendedor); oligopólio (poucos vendedores, interdependência); concorrência monopolística (diferenciação).</li><li>Custos: fixos, variáveis, totais, médios e <b>marginal</b>. Empresas maximizam lucro onde receita marginal = custo marginal. Economias de escala: custo médio decresce com a produção.</li><li>Falhas de mercado: externalidades, bens públicos, assimetria de informação.</li></ul>","MANKIW; PINDYCK; RUBINFELD."],
["4. Macroeconomia","<ul><li><b>PIB</b>: valor dos bens e serviços finais produzidos. Ótica da despesa: <code>Y = C + I + G + X − M</code>.</li><li><b>Inflação</b>: aumento geral e persistente de preços (medida no Brasil por índices como o IPCA).</li><li><b>Política monetária</b>: controle de juros e liquidez (no Brasil, o Copom define a meta da taxa Selic). Alta de juros tende a conter demanda e inflação. <b>Política fiscal</b>: gastos e tributos do governo.</li><li><b>Câmbio</b>: depreciação da moeda local encarece importações e favorece exportações. <b>Balanço de pagamentos</b>: transações correntes, conta capital e conta financeira.</li></ul>","MANKIW, N. G. <i>Macroeconomia</i>; VASCONCELLOS."]
],
mapa:`ECONOMIA
├── Micro: demanda/oferta, equilíbrio; deslocamento × movimento
│   ├── Elasticidade: |E| > 1 elástica; inelástica → preço ↑ = receita ↑
│   └── Mercados: concorrência perfeita, monopólio, oligopólio
└── Macro: PIB = C + I + G + X − M; inflação (IPCA); Selic (Copom)
    └── Câmbio; balanço de pagamentos; política fiscal × monetária`,
q:[
Q("Se o preço de um bem aumenta 10% e a quantidade demandada diminui 5%, a elasticidade-preço da demanda, em módulo, é",["0,5, e a demanda é inelástica.","2,0, e a demanda é elástica.","1,0, e a demanda é unitária.","0,5, e a demanda é elástica.","5,0, e a demanda é inelástica."],0,["|E| = 5/10 = 0,5 < 1: inelástica.","Seria o resultado de dividir 10 por 5.","Exigiria variações iguais.","0,5 indica demanda inelástica, não elástica.","Erro de cálculo."],"Mankiw; Pindyck e Rubinfeld."),
Q("Um aumento da renda dos consumidores, para um bem normal, tende a",["deslocar a curva de demanda para a direita.","deslocar a curva de demanda para a esquerda.","provocar movimento ao longo da curva de oferta apenas.","reduzir a quantidade de equilíbrio.","não afetar a demanda."],0,["Bens normais têm demanda crescente com a renda.","Seria o caso de um bem inferior.","O efeito primário é sobre a demanda.","Com demanda maior, a quantidade de equilíbrio tende a aumentar.","A renda é determinante da demanda."],"Mankiw."),
Q("Pela ótica da despesa, o PIB é dado por",["C + I + G + X − M.","C + I + G − X + M.","C + I − G + X − M.","C − I + G + X + M.","apenas C + G."],0,["Consumo + investimento + gastos do governo + exportações − importações.","Sinais de X e M invertidos.","G tem sinal positivo.","I tem sinal positivo e M, negativo.","Omite componentes."],"Mankiw; Vasconcellos."),
Q("Se o preço do etanol aumenta, mantidas as demais condições, tende a aumentar a demanda por gasolina, o que ilustra que os dois bens são",["complementares.","substitutos.","inferiores.","bens públicos.","de Giffen."],1,["Complementares teriam demanda que cai quando o preço do outro sobe.","Elasticidade cruzada positiva indica bens substitutos.","Bem inferior refere-se à relação com a renda.","Bem público refere-se a não rivalidade e não exclusão.","Bem de Giffen é caso particular de bem inferior."],"Mankiw."),
Q("Uma política monetária contracionista, como a elevação da taxa Selic, tende, em geral, a",["estimular a demanda agregada e a inflação.","reduzir a demanda agregada e conter a inflação.","reduzir tributos diretamente.","aumentar os gastos do governo.","depreciar automaticamente o real sem outros efeitos."],1,["Seria o efeito de política expansionista.","Juros maiores encarecem crédito e reduzem consumo e investimento.","Alterar tributos é política fiscal.","Gastos do governo são política fiscal.","Os efeitos cambiais dependem de vários fatores; o efeito principal é sobre demanda e inflação."],"Mankiw, Macroeconomia.")
]});
