MODS.push({n:9,t:"Matemática: lógica, conjuntos, funções, logaritmos, trigonometria, matrizes e progressões",edital:"Lógica; conjuntos; relações; funções; logaritmos; trigonometria; cálculo vetorial e matricial; progressões; sistemas de numeração",
alerta:"Módulo de revisão. A profundidade cobrada não é informada no edital; pratique com muitas questões de provas anteriores da Cesgranrio.",
intro:"Resumo das ferramentas matemáticas listadas no edital, com foco nas fórmulas e propriedades mais cobradas.",
obj:["Negar e simplificar proposições.","Resolver problemas com conjuntos e classificar relações e funções.","Usar propriedades de logaritmos e relações trigonométricas.","Operar matrizes e vetores.","Aplicar PA e PG e converter entre bases de numeração."],
secs:[
["1. Lógica proposicional","<ul><li>Conectivos: ∧ (e), ∨ (ou), → (se...então), ↔ (se e somente se), ~ (não).</li><li>A condicional <code>p → q</code> só é falsa quando p é verdadeira e q é falsa.</li><li>Negação: <code>~(p → q) ≡ p ∧ ~q</code>; De Morgan: <code>~(p ∧ q) ≡ ~p ∨ ~q</code> e <code>~(p ∨ q) ≡ ~p ∧ ~q</code>.</li><li>Equivalência: <code>p → q ≡ ~q → ~p ≡ ~p ∨ q</code>.</li><li>Quantificadores: negar \"todo A é B\" resulta em \"algum A não é B\".</li></ul>","Matemática discreta (p. ex., GERSTING, J. <i>Fundamentos Matemáticos para a Ciência da Computação</i>, LTC)."],
["2. Conjuntos, relações e funções","<ul><li><code>|A ∪ B| = |A| + |B| − |A ∩ B|</code>; complemento; produto cartesiano.</li><li>Relação: reflexiva, simétrica, antissimétrica, transitiva. <b>Equivalência</b> = reflexiva + simétrica + transitiva. <b>Ordem parcial</b> = reflexiva + antissimétrica + transitiva.</li><li>Função: cada elemento do domínio tem <b>exatamente uma</b> imagem. Injetora, sobrejetora e bijetora (admite inversa). Afim <code>f(x) = ax + b</code>; quadrática com vértice em <code>x = −b/2a</code> e <code>Δ = b² − 4ac</code>; exponencial <code>aˣ</code>.</li></ul>","IEZZI, G.; MURAKAMI, C. <i>Fundamentos de Matemática Elementar</i>, Atual."],
["3. Logaritmos","<ul><li><code>log_b(xy) = log_b x + log_b y</code>; <code>log_b(x/y) = log_b x − log_b y</code>; <code>log_b xᵏ = k·log_b x</code>.</li><li>Mudança de base: <code>log_b x = log_c x / log_c b</code>. <code>log_b b = 1</code>; <code>log_b 1 = 0</code>.</li><li>Existência: base positiva e diferente de 1; logaritmando positivo.</li></ul>","IEZZI; MURAKAMI."],
["4. Trigonometria","<ul><li><code>sen²x + cos²x = 1</code>; <code>tg x = sen x/cos x</code>; π rad = 180°.</li><li>Valores notáveis: sen 30° = 1/2, sen 45° = √2/2, sen 60° = √3/2 (e cos nos ângulos complementares).</li><li>Lei dos senos e dos cossenos para triângulos quaisquer: <code>a² = b² + c² − 2bc·cos A</code>.</li></ul>","IEZZI et al."],
["5. Vetores e matrizes","<ul><li>Produto escalar: <code>u·v = Σ uᵢvᵢ = |u||v|cos θ</code>; vetores ortogonais têm produto escalar nulo. Módulo: <code>|u| = √(u·u)</code>.</li><li>Produto de matrizes: (m×n)·(n×p) resulta em m×p (linhas por colunas), não é comutativo.</li><li>Determinante 2×2: <code>ad − bc</code>. A matriz é invertível se det ≠ 0. <code>det(AB) = det A · det B</code>.</li></ul>","BOLDRINI, J. L. et al. <i>Álgebra Linear</i>, Harbra."],
["6. Progressões e sistemas de numeração","<ul><li><b>PA</b>: <code>aₙ = a₁ + (n − 1)r</code>; <code>Sₙ = (a₁ + aₙ)·n/2</code>.</li><li><b>PG</b>: <code>aₙ = a₁·qⁿ⁻¹</code>; <code>Sₙ = a₁(qⁿ − 1)/(q − 1)</code>; soma infinita com |q| &lt; 1: <code>a₁/(1 − q)</code>.</li><li><b>Numeração posicional</b>: em base b, cada dígito vale dígito × bᵖᵒˢⁱçãᵒ. Binário para decimal: some as potências de 2 dos bits 1. Decimal para binário: divisões sucessivas por 2. Hexadecimal usa 0 a 9 e A a F; 1 byte = 8 bits.</li></ul>","IEZZI et al."]
],
mapa:`MATEMÁTICA
├── Lógica: ~(p→q) ≡ p ∧ ~q; contrapositiva; De Morgan
├── Conjuntos: |A∪B| = |A| + |B| − |A∩B|; relações e funções
├── Log: produto → soma; potência → coeficiente; mudança de base
├── Trigonometria: sen² + cos² = 1; ângulos notáveis
├── Vetores/matrizes: produto escalar; det 2×2 = ad − bc
└── PA/PG; bases 2, 8, 10, 16`,
q:[
Q("A negação da proposição \"Se o duto está pressurizado, então a válvula está fechada\" é",["Se o duto não está pressurizado, então a válvula não está fechada.","O duto está pressurizado e a válvula não está fechada.","O duto não está pressurizado e a válvula está fechada.","Se a válvula está fechada, então o duto está pressurizado.","O duto não está pressurizado ou a válvula está fechada."],1,["Não é a negação; é a inversa da condicional.","~(p → q) ≡ p ∧ ~q.","Não corresponde à negação.","É a recíproca, não a negação.","Esta é a forma equivalente à própria condicional (~p ∨ q)."],"Lógica proposicional."),
Q("Em um grupo de 100 clientes, 60 compram gasolina, 45 compram diesel e 20 compram ambos. O número de clientes que não compram nenhum dos dois é",["5.","10.","15.","20.","25."],2,["Erro de cálculo.","Erro de cálculo.","|A ∪ B| = 60 + 45 − 20 = 85; 100 − 85 = 15.","Corresponde ao número dos que compram ambos.","Erro de cálculo."],"Princípio da inclusão-exclusão."),
Q("O valor de log₂ 32 + log₃ 81 é",["7.","8.","9.","10.","12."],2,["Erro de cálculo.","Erro de cálculo.","log₂ 32 = 5 e log₃ 81 = 4, soma 9.","Erro de cálculo.","Erro de cálculo."],"Definição de logaritmo."),
Q("Em uma progressão aritmética com primeiro termo 5 e razão 3, a soma dos 20 primeiros termos é",["570.","600.","670.","700.","1140."],2,["Erro de cálculo.","Erro de cálculo.","a₂₀ = 5 + 19·3 = 62; S = (5 + 62)·20/2 = 670.","Erro de cálculo.","Erro de cálculo (dobro do valor de 570)."],"Progressão aritmética."),
Q("O número binário 101101 corresponde, na base decimal, a",["35.","41.","45.","49.","53."],2,["Erro de conversão.","Erro de conversão.","32 + 8 + 4 + 1 = 45.","Erro de conversão.","Erro de conversão."],"Sistemas de numeração posicionais.")
]});
