MODS.push({n:11,t:"Gases, termologia, unidades e conversões",edital:"Relações entre volume, pressão e temperatura; termologia; sistemas de unidades; conversões",
intro:"Este módulo reúne a base física do edital: comportamento de gases, escalas de temperatura, calor e conversão de unidades típicas do setor de petróleo (barril, m³, atm, psi).",
obj:["Aplicar a equação dos gases ideais e as transformações isotérmica, isobárica e isocórica.","Converter escalas de temperatura (°C, °F, K).","Calcular calor sensível e latente.","Converter unidades de volume, pressão e energia."],
secs:[
["1. Gases ideais","<p><code>PV = nRT</code>, com T sempre em <b>kelvin</b> (K = °C + 273,15; na prática, +273). R ≈ 0,082 atm·L/(mol·K) ≈ 8,314 J/(mol·K).</p><ul><li><b>Boyle</b> (T constante): P₁V₁ = P₂V₂.</li><li><b>Charles</b> (P constante): V₁/T₁ = V₂/T₂.</li><li><b>Gay-Lussac</b> (V constante): P₁/T₁ = P₂/T₂.</li><li>Geral: P₁V₁/T₁ = P₂V₂/T₂.</li><li>Volume molar nas CNTP (0 °C, 1 atm): 22,4 L/mol.</li></ul>","Física básica do ensino médio e superior (p. ex., HALLIDAY; RESNICK; WALKER, <i>Fundamentos de Física</i>, LTC)."],
["2. Termologia","<ul><li>Escalas: <code>F = 1,8·C + 32</code>; <code>K = C + 273</code>.</li><li>Calor sensível: <code>Q = m·c·ΔT</code> (muda a temperatura). Água: c = 1 cal/(g·°C) ≈ 4,18 J/(g·K).</li><li>Calor latente: <code>Q = m·L</code> (muda o estado, temperatura constante).</li><li>Dilatação linear: <code>ΔL = L₀·α·ΔT</code>; superficial ≈ 2α; volumétrica ≈ 3α. Líquidos dilatam em tanques com a temperatura, o que importa na medição de volumes.</li><li>Transmissão de calor: condução, convecção e irradiação.</li></ul>","HALLIDAY; RESNICK; WALKER."],
["3. Sistemas de unidades e conversões","<table><tr><th>Grandeza</th><th>Conversão útil</th></tr><tr><td>Volume</td><td>1 bbl (barril) = 42 galões US ≈ 158,987 L ≈ 0,159 m³; 1 m³ = 1000 L ≈ 6,29 bbl; 1 galão US ≈ 3,785 L; 1 ft³ ≈ 28,317 L</td></tr><tr><td>Pressão</td><td>1 atm = 101 325 Pa = 760 mmHg ≈ 1,013 bar; 1 bar = 10⁵ Pa; 1 psi ≈ 6895 Pa; 1 kgf/cm² ≈ 98 066 Pa</td></tr><tr><td>Energia</td><td>1 cal = 4,1868 J; 1 kWh = 3,6 MJ; 1 BTU ≈ 1055 J</td></tr><tr><td>Comprimento e velocidade</td><td>1 milha náutica = 1852 m; 1 nó = 1 milha náutica/h ≈ 0,514 m/s</td></tr><tr><td>Massa e densidade</td><td>ρ = m/V; conversão volume ↔ massa depende da densidade do produto</td></tr></table><p>SI: metro, quilograma, segundo, ampère, kelvin, mol e candela. Prefixos: k (10³), M (10⁶), G (10⁹), m (10⁻³), µ (10⁻⁶).</p>","INMETRO (Sistema Internacional de Unidades); fatores de conversão padrão."]
],
mapa:`FÍSICA APLICADA
├── Gases: PV = nRT (T em K)
│   ├── Boyle (T cte)  Charles (P cte)  Gay-Lussac (V cte)
├── Termologia: F = 1,8C + 32; K = C + 273
│   ├── Q = m·c·ΔT (sensível)   Q = m·L (latente)
│   └── Dilatação: ΔL = L0·α·ΔT
└── Unidades: 1 bbl ≈ 159 L; 1 atm = 101 325 Pa; 1 cal = 4,1868 J`,
q:[
Q("Dois mols de um gás ideal ocupam, a 300 K e 1 atm, um volume de (use R = 0,082 atm·L/mol·K)",["24,6 L.","49,2 L.","98,4 L.","4,92 L.","12,3 L."],1,["Corresponde a 1 mol.","V = nRT/P = 2·0,082·300/1 = 49,2 L.","Seria o resultado com 4 mols.","Erro de fator de 10.","Corresponde a 0,5 mol."],"Equação dos gases ideais."),
Q("Um gás ideal, mantido em volume constante, está a 27 °C e 2 atm. Ao ser aquecido até 127 °C, sua pressão, em atm, passa a ser aproximadamente",["2,67.","4,00.","9,41.","1,50.","2,00."],0,["P₂ = P₁·T₂/T₁ = 2·400/300 ≈ 2,67 atm (Gay-Lussac, com T em kelvin).","Resultaria de dobrar a pressão, sem base na relação em kelvin.","Resultaria do erro de usar as temperaturas em °C.","A pressão aumenta com o aquecimento a volume constante.","A pressão não permanece constante."],"Lei de Gay-Lussac."),
Q("Uma temperatura de 50 °C corresponde, nas escalas Kelvin e Fahrenheit, respectivamente, a",["323 K e 122 °F.","223 K e 122 °F.","323 K e 90 °F.","273 K e 50 °F.","373 K e 212 °F."],0,["K = 50 + 273 = 323; F = 1,8·50 + 32 = 122.","223 K seria −50 °C.","F = 1,8·50 + 32 = 122, não 90.","Ignora a conversão.","São os valores do ponto de ebulição da água (100 °C)."],"Conversão entre escalas termométricas."),
Q("Para aquecer 2 kg de água líquida de 20 °C a 70 °C, sem mudança de estado, considerando c = 1 cal/(g·°C), é necessária uma quantidade de calor de",["10 kcal.","50 kcal.","100 kcal.","140 kcal.","1000 kcal."],2,["Erro de escala na conta.","Usaria massa de 1 kg.","Q = m·c·ΔT = 2000·1·50 = 100 000 cal = 100 kcal.","Confunde ΔT com a soma das temperaturas (70 + 20 = 90) ou outro erro.","Erro de fator de 10."],"Calor sensível: Q = m·c·ΔT."),
Q("Considerando 1 barril ≈ 158,987 litros, um volume de 1000 barris equivale a aproximadamente",["63 m³.","159 m³.","1590 m³.","6,29 m³.","15,9 m³."],1,["Resultado de dividir por 15,9 em vez de multiplicar por 0,159.","1000 · 158,987 L = 158 987 L ≈ 159 m³.","Erro de fator de 10.","Corresponde a 1 m³ em barris (≈ 6,29), não o inverso.","Erro de fator de 10."],"Fatores de conversão padrão da indústria do petróleo.")
]});
