MODS.push({n:12,t:"Gestão de estoques e materiais",fora:true,edital:"não consta por nome no Anexo IV (pode aparecer sob \"noções elementares de logística\")",
alerta:"Complemento fora do Anexo IV. Fórmulas e conceitos clássicos da literatura; não foram conferidos contra provas anteriores.",
intro:"Estoques equilibram oferta e demanda e custam dinheiro. A gestão busca o menor custo total com o nível de serviço desejado. As questões costumam envolver classificação ABC, lote econômico, ponto de pedido, estoque de segurança e indicadores.",
obj:["Distinguir tipos de estoque e de custos.","Classificar itens pela curva ABC.","Calcular lote econômico, ponto de pedido e estoque de segurança.","Calcular giro e cobertura.","Diferenciar sistemas de reposição e critérios de avaliação de estoque."],
secs:[
["1. Tipos de estoque e custos","<ul><li>Tipos: de <b>ciclo</b> (lote), de <b>segurança</b> (incertezas de demanda e prazo), <b>sazonal</b> ou de antecipação, em <b>trânsito</b> (pipeline) e especulativo.</li><li>Custos: de <b>pedido</b> (fixos por pedido), de <b>manutenção</b> (capital, armazenagem, seguros, obsolescência, perdas) e de <b>falta</b> (ruptura: vendas perdidas, paradas).</li></ul>","BALLOU, R. H., <i>Gerenciamento da Cadeia de Suprimentos/Logística Empresarial</i>; CHOPRA; MEINDL; SLACK, N. et al., <i>Administração da Produção</i>."],
["2. Classificação ABC (Pareto)","<p>Ordena os itens por valor anual de consumo (consumo × custo unitário). Classe <b>A</b>: poucos itens que concentram a maior parte do valor (controle rigoroso); <b>B</b>: intermediária; <b>C</b>: muitos itens de pequeno valor (controle simples). Os percentuais típicos (por exemplo, ~20% dos itens para ~80% do valor) são regra prática, não norma. A classificação por <b>criticidade</b> (efeito da falta) pode diferir da de valor, sobretudo em manutenção. XYZ classifica pela previsibilidade da demanda.</p>","BALLOU; SLACK et al."],
["3. Lote econômico de compra (LEC/EOQ)","<p><code>Q* = √(2·D·S / H)</code>, com D = demanda anual, S = custo por pedido, H = custo de manter uma unidade por ano. No ponto ótimo, <b>custo anual de pedir = custo anual de manter</b>. Hipóteses: demanda constante e conhecida, reposição instantânea, sem falta, preço constante. Número de pedidos por ano = D/Q*; intervalo entre pedidos = Q*/D.</p>","CHOPRA; MEINDL; BALLOU."],
["4. Ponto de pedido e estoque de segurança","<ul><li>Ponto de pedido (reposição): <code>PP = d·L + ES</code>, com d = demanda média por período e L = prazo de ressuprimento (lead time).</li><li>Estoque de segurança com demanda variável e prazo constante: <code>ES = z·σd·√L</code>. O fator z depende do nível de serviço: 90% → 1,28; 95% → 1,65; 99% → 2,33.</li><li>Sistemas: <b>revisão contínua</b> (pedido de Q quando atinge o ponto de pedido) e <b>revisão periódica</b> (a cada intervalo fixo, repõe até um nível máximo).</li></ul>","CHOPRA; MEINDL."],
["5. Indicadores, avaliação e MRP","<ul><li><b>Giro</b> = consumo (ou CMV) do período / estoque médio. <b>Cobertura</b> = estoque / consumo médio por período (em dias ou meses); giro e cobertura são inversos.</li><li><b>Acuracidade</b> do inventário = itens com saldo físico igual ao registrado / itens contados. <b>Inventário rotativo</b> (cíclico) conta parte dos itens ao longo do ano; o geral conta todos em uma data.</li><li>Avaliação: <b>PEPS</b> (primeiro que entra, primeiro que sai), <b>custo médio ponderado</b>. O <b>UEPS</b> não é admitido pelo CPC 16 (IAS 2).</li><li><b>MRP</b>: planeja necessidades de itens de <b>demanda dependente</b> a partir do plano mestre, da lista de materiais e dos estoques e prazos.</li></ul>","SLACK et al.; CPC 16 (R1) (Estoques)."]
],
mapa:`ESTOQUES
├── Tipos: ciclo, segurança, sazonal, em trânsito | Custos: pedir, manter, falta
├── ABC: valor de consumo (Pareto) | XYZ: previsibilidade | criticidade
├── LEC: Q* = √(2DS/H) | custo de pedir = custo de manter
├── PP = d·L + ES | ES = z·σ·√L
├── Giro = consumo/estoque médio | Cobertura = estoque/consumo
└── PEPS, custo médio (UEPS não admitido pelo CPC 16) | MRP`,
q:[
Q("Uma empresa consome 1.200 unidades por ano de um item, com custo de emissão de pedido de R$ 50,00 e custo de manutenção de R$ 6,00 por unidade por ano. O lote econômico de compra, em unidades, é aproximadamente",["100.","141.","200.","240.","400."],1,["Sem base no cálculo.","Q* = √(2·1200·50/6) = √20.000 ≈ 141.","Sem base no cálculo.","Sem base no cálculo.","Sem base no cálculo."],"Fórmula do LEC (Chopra e Meindl; Ballou)."),
Q("Um item tem demanda média de 20 unidades por dia, prazo de ressuprimento de 5 dias e estoque de segurança de 30 unidades. O ponto de pedido é de",["100.","110.","130.","150.","600."],2,["Ignora o estoque de segurança.","Sem base no cálculo.","PP = 20·5 + 30 = 130.","Sem base no cálculo.","Multiplicaria todos os fatores."],"Sistema de revisão contínua."),
Q("Na classificação ABC de estoques pelo valor de consumo, os itens da classe A são",["numerosos e de baixo valor, com controle simples.","poucos e responsáveis pela maior parte do valor consumido, merecendo controle mais rigoroso.","os de menor criticidade para a operação.","todos os itens de demanda constante.","os que têm giro mais baixo."],1,["Descreve a classe C.","Princípio de Pareto aplicado ao valor de consumo.","Valor e criticidade são critérios diferentes.","A classe A não depende de a demanda ser constante.","O giro não define a classe."],"Ballou; Slack et al."),
Q("Se o consumo anual de um item é de 2.400 unidades e o estoque médio é de 400 unidades, o giro anual e a cobertura são, respectivamente,",["6 vezes por ano e 2 meses.","4 vezes por ano e 3 meses.","6 vezes por ano e 6 meses.","0,17 vez por ano e 2 meses.","12 vezes por ano e 1 mês."],0,["Giro = 2400/400 = 6; cobertura = 12/6 = 2 meses.","Sem base no cálculo.","A cobertura não é 6 meses.","Inverte a razão do giro.","Sem base no cálculo."],"Indicadores de estoque."),
Q("Para um nível de serviço de 95% (z = 1,65), desvio padrão da demanda diária de 10 unidades e prazo de ressuprimento de 4 dias, o estoque de segurança é de aproximadamente",["16,5.","33.","66.","41.","20."],1,["Ignora o efeito do prazo.","ES = 1,65·10·√4 = 33.","Multiplica pelo prazo em vez de √L.","Sem base no cálculo.","Sem base no cálculo."],"ES = z·σd·√L (Chopra e Meindl).")
]});
