MODS.push({n:13,t:"Incoterms 2020",fora:true,edital:"não consta por nome no Anexo IV (comércio internacional e afretamento cabem em \"logística\" e \"comercialização\")",
alerta:"Complemento fora do Anexo IV. Baseado na versão Incoterms 2020 da ICC (vigente desde 1/1/2020); confira se há versão mais nova antes da prova. Não consegui acessar o texto oficial (pago). Em contratos de petróleo o mercado também usa termos que não são Incoterms.",
intro:"Incoterms são regras da Câmara de Comércio Internacional (ICC) que definem, em contratos de compra e venda, obrigações de entrega, transferência de riscos e divisão de custos entre vendedor e comprador. São muito usados em cargas de petróleo e derivados (FOB, CFR, CIF).",
obj:["Identificar os 11 termos e seus dois grupos.","Determinar onde o risco e os custos passam ao comprador.","Distinguir obrigações de frete, seguro e desembaraço.","Reconhecer as mudanças da versão 2020."],
secs:[
["1. Natureza e limites","<p>Os Incoterms tratam de entrega, riscos, custos, desembaraço e documentos. <b>Não tratam</b> de transferência de propriedade, preço, forma de pagamento, lei aplicável, solução de controvérsias ou consequências de quebra de contrato. Devem ser citados com o local e a versão (por exemplo, \"FOB Santos, Incoterms 2020\").</p>","ICC, <i>Incoterms 2020</i>."],
["2. Os 11 termos","<table><tr><th>Grupo</th><th>Termo</th><th>Risco passa ao comprador</th><th>Observações</th></tr><tr><td rowspan=\"7\">Qualquer modal</td><td>EXW</td><td>Mercadoria à disposição no local do vendedor</td><td>Comprador contrata frete e faz desembaraço de exportação</td></tr><tr><td>FCA</td><td>Entrega ao transportador indicado pelo comprador</td><td>Vendedor faz desembaraço de exportação</td></tr><tr><td>CPT</td><td>Entrega ao 1º transportador</td><td>Vendedor paga frete até o destino</td></tr><tr><td>CIP</td><td>Entrega ao 1º transportador</td><td>Vendedor paga frete e seguro (cobertura ampla, Institute Cargo Clauses A)</td></tr><tr><td>DAP</td><td>Mercadoria à disposição no destino, pronta para descarga</td><td>Vendedor arca com o transporte até o destino</td></tr><tr><td>DPU</td><td>Mercadoria descarregada no destino</td><td>Substituiu o DAT; único em que o vendedor descarrega</td></tr><tr><td>DDP</td><td>À disposição no destino, desembaraçada para importação</td><td>Máxima obrigação do vendedor, inclusive tributos de importação</td></tr><tr><td rowspan=\"4\">Marítimo e hidroviário</td><td>FAS</td><td>Ao lado do navio no porto de embarque</td><td>Comprador contrata o navio</td></tr><tr><td>FOB</td><td>A bordo do navio no porto de embarque</td><td>Comprador contrata frete</td></tr><tr><td>CFR</td><td>A bordo do navio no porto de embarque</td><td>Vendedor paga frete até o porto de destino</td></tr><tr><td>CIF</td><td>A bordo do navio no porto de embarque</td><td>Vendedor paga frete e seguro mínimo (Institute Cargo Clauses C)</td></tr></table><p>Nos grupos com frete pago pelo vendedor (CPT, CIP, CFR, CIF), <b>custo</b> e <b>risco</b> se dividem em pontos diferentes: o risco passa na origem, mas o vendedor paga o transporte até o destino.</p>","ICC, <i>Incoterms 2020</i>."],
["3. Mudanças da versão 2020","<ul><li><b>DAT</b> deu lugar ao <b>DPU</b> (Delivered at Place Unloaded).</li><li><b>CIP</b> passou a exigir seguro com cobertura máxima (ICC A); CIF manteve cobertura mínima (ICC C).</li><li><b>FCA</b> pode prever que o comprador instrua o transportador a emitir conhecimento de embarque com nota de \"embarcado\" ao vendedor.</li><li>Uso de transporte próprio permitido em FCA, DAP, DPU e DDP; organização dos custos por obrigação.</li></ul>","ICC, <i>Incoterms 2020</i>."]
],
mapa:`INCOTERMS 2020
├── Não tratam de propriedade, preço, pagamento, lei aplicável
├── Qualquer modal: EXW, FCA, CPT, CIP, DAP, DPU, DDP
├── Aquaviário: FAS, FOB, CFR, CIF
├── Frete pago pelo vendedor: CPT, CIP, CFR, CIF (risco passa na origem)
├── Seguro: CIP (ICC A) | CIF (ICC C)
└── 2020: DAT → DPU; FCA com BL "on board"`,
q:[
Q("Em uma venda FOB (Incoterms 2020), o risco de perda ou dano da mercadoria passa do vendedor ao comprador quando a mercadoria",["é colocada à disposição no estabelecimento do vendedor.","é entregue a bordo do navio indicado pelo comprador, no porto de embarque.","chega ao porto de destino.","é descarregada no destino.","passa pela alfândega de importação."],1,["Descreve o EXW.","FOB: entrega a bordo do navio no porto de embarque.","No CFR/CIF o risco também passa no embarque; o destino é ponto de custo, não de risco.","Descreve o DPU.","Descreve o DDP em parte (desembaraço de importação)."],"ICC, Incoterms 2020."),
Q("No Incoterm CIF (2020), o vendedor",["assume o risco até o porto de destino.","contrata e paga frete e seguro com cobertura mínima, mas o risco passa ao comprador quando a mercadoria está a bordo no porto de embarque.","apenas coloca a mercadoria à disposição no seu estabelecimento.","é responsável pelo desembaraço de importação.","descarrega a mercadoria no destino."],1,["O risco passa no embarque.","Vendedor paga frete e seguro (ICC C); risco passa a bordo no embarque.","Descreve o EXW.","O desembaraço de importação é do comprador, salvo DDP.","Descreve o DPU."],"ICC, Incoterms 2020."),
Q("Entre os termos abaixo, é utilizável exclusivamente em transporte marítimo e hidroviário:",["EXW.","FCA.","CPT.","DAP.","FOB."],4,["EXW serve a qualquer modal.","FCA serve a qualquer modal.","CPT serve a qualquer modal.","DAP serve a qualquer modal.","FOB, FAS, CFR e CIF são exclusivos do modal aquaviário."],"ICC, Incoterms 2020."),
Q("O Incoterm em que o vendedor assume a máxima obrigação, incluindo o desembaraço para importação e o pagamento de tributos de importação no país de destino, é",["EXW.","FOB.","CIF.","DPU.","DDP."],4,["No EXW o vendedor tem a mínima obrigação.","No FOB o comprador contrata o frete.","No CIF o vendedor paga frete e seguro, sem desembaraço de importação.","No DPU o vendedor descarrega no destino, sem desembaraço de importação.","DDP: entrega desembaraçada para importação, com tributos pelo vendedor."],"ICC, Incoterms 2020."),
Q("Em relação às mudanças trazidas pelos Incoterms 2020, é correto afirmar que",["o termo DAT foi substituído pelo DPU e o CIP passou a exigir cobertura de seguro ampla (Institute Cargo Clauses A).","o CIF passou a exigir cobertura de seguro máxima.","foram criados os termos DES e DEQ.","os Incoterms passaram a regular a transferência de propriedade.","o FOB passou a ser permitido para transporte rodoviário."],0,["DAT → DPU; CIP com ICC A.","O CIF manteve cobertura mínima (ICC C).","DES e DEQ foram retirados na versão de 2010.","Os Incoterms não tratam de propriedade.","O FOB continua exclusivo do modal aquaviário."],"ICC, Incoterms 2020.")
]});
