MODS.push({n:14,t:"Negociação",fora:true,edital:"não consta por nome no Anexo IV (útil para comercialização e contratos)",
alerta:"Complemento fora do Anexo IV. Conceitos consagrados (Harvard, Thomas-Kilmann); nada aqui vem de norma da Transpetro.",
intro:"Negociar é buscar um acordo entre partes com interesses parcialmente conflitantes. Em comercialização e suprimentos, a qualidade da preparação costuma decidir o resultado.",
obj:["Diferenciar negociação distributiva e integrativa.","Aplicar os quatro princípios do método de Harvard.","Definir BATNA, ZOPA e ponto de reserva.","Reconhecer estilos de negociação.","Relacionar negociação e licitação nas estatais."],
secs:[
["1. Conceitos básicos","<ul><li><b>Negociação distributiva</b> (soma zero): ganho de um é perda do outro, foco em uma variável (em geral preço). <b>Integrativa</b> (ganha-ganha): amplia o valor total combinando várias variáveis (prazo, volume, qualidade, serviços).</li><li><b>Posições</b> (o que se pede) × <b>interesses</b> (por que se pede).</li><li><b>BATNA</b> (MAPAN, melhor alternativa à negociação de um acordo): o que a parte fará se não houver acordo. Define o <b>ponto de reserva</b>, o pior acordo aceitável.</li><li><b>ZOPA</b> (zona de possível acordo): intervalo entre os pontos de reserva das partes; só existe se houver sobreposição.</li><li><b>Ancoragem</b>: a primeira oferta influencia o resultado.</li></ul>","FISHER, R.; URY, W.; PATTON, B., <i>Como Chegar ao Sim</i>; LEWICKI, R. et al., <i>Fundamentos da Negociação</i>."],
["2. Método de Harvard (negociação baseada em princípios)","<ol><li>Separar as <b>pessoas</b> do problema.</li><li>Focar em <b>interesses</b>, não em posições.</li><li>Inventar <b>opções de ganho mútuo</b>.</li><li>Insistir em <b>critérios objetivos</b> (preços de mercado, normas, precedentes).</li></ol><p>Complemento: conhecer e melhorar a própria BATNA.</p>","FISHER; URY; PATTON."],
["3. Fases e preparação","<p>Preparação (objetivos, BATNA, ponto de reserva, informações sobre a outra parte), abertura, exploração de interesses, barganha e concessões, fechamento e implementação/acompanhamento. Em compras, pontos de alavancagem: volume, prazo de contrato, especificação, condições de pagamento e <b>custo total de propriedade</b>.</p>","LEWICKI et al."],
["4. Estilos de conflito (Thomas-Kilmann)","<table><tr><th>Estilo</th><th>Assertividade</th><th>Cooperação</th></tr><tr><td>Competição</td><td>Alta</td><td>Baixa</td></tr><tr><td>Colaboração</td><td>Alta</td><td>Alta</td></tr><tr><td>Compromisso</td><td>Média</td><td>Média</td></tr><tr><td>Evitação</td><td>Baixa</td><td>Baixa</td></tr><tr><td>Acomodação</td><td>Baixa</td><td>Alta</td></tr></table>","THOMAS, K.; KILMANN, R. (Instrumento de modos de conflito)."],
["5. Negociação em estatais","<p>Nas licitações da Lei 13.303, a negociação é <b>fase obrigatória</b>: a empresa deve negociar condições mais vantajosas com o primeiro colocado e, se o preço continuar acima do orçamento estimado, com os demais na ordem; se ninguém chegar ao orçamento, a licitação é revogada (art. 57). A negociação não pode violar os princípios da igualdade e da vinculação ao instrumento convocatório. Nas contratações diretas, a justificativa do preço é exigida (art. 30, §3º).</p>","Lei 13.303/2016, arts. 30 e 57 (texto conferido)."]
],
mapa:`NEGOCIAÇÃO
├── Distributiva (soma zero) × integrativa (ganha-ganha)
├── Posições × interesses | BATNA → ponto de reserva | ZOPA
├── Harvard: pessoas ≠ problema; interesses; opções; critérios objetivos
├── Estilos: competição, colaboração, compromisso, evitação, acomodação
└── Estatais: negociação obrigatória com o 1º colocado (art. 57, Lei 13.303)`,
q:[
Q("Na literatura de negociação, a BATNA (ou MAPAN) representa",["o preço inicial que uma das partes apresenta.","a melhor alternativa disponível para a parte caso não haja acordo.","o intervalo entre as ofertas das duas partes.","a concessão máxima que a outra parte aceita.","o critério objetivo de mercado."],1,["Descreve a oferta inicial ou âncora.","Melhor alternativa à negociação de um acordo.","Descreve a ZOPA em parte.","A concessão máxima da outra parte é o ponto de reserva dela.","Critérios objetivos são outro princípio do método de Harvard."],"Fisher, Ury e Patton."),
Q("A zona de possível acordo (ZOPA) existe quando",["os pontos de reserva das partes se sobrepõem.","as duas partes têm a mesma posição inicial.","uma das partes abandona a negociação.","as partes adotam o estilo de evitação.","há mediador presente."],0,["ZOPA é a sobreposição entre os pontos de reserva.","A posição inicial não define a ZOPA.","Sem acordo não há ZOPA por definição, mas não é essa a definição.","Estilos não definem ZOPA.","A mediação é independente da ZOPA."],"Lewicki et al."),
Q("Segundo o método de Harvard, uma negociação baseada em princípios deve",["concentrar-se em posições, para evitar exposição de interesses.","separar as pessoas do problema, focar em interesses, gerar opções de ganho mútuo e insistir em critérios objetivos.","adotar sempre a postura competitiva.","evitar critérios externos de mercado.","dispensar a preparação prévia."],1,["O método recomenda focar em interesses, não em posições.","Os quatro princípios do método.","A competição é apenas um dos estilos.","Critérios objetivos são um dos princípios.","A preparação é central."],"Fisher, Ury e Patton."),
Q("No modelo de Thomas-Kilmann, o estilo caracterizado por alta assertividade e alta cooperação é",["competição.","evitação.","acomodação.","colaboração.","compromisso."],3,["Competição: alta assertividade e baixa cooperação.","Evitação: baixas em ambas.","Acomodação: baixa assertividade e alta cooperação.","Colaboração: alta em ambas.","Compromisso: nível médio em ambas."],"Thomas e Kilmann."),
Q("De acordo com o art. 57 da Lei 13.303/2016, se, após a negociação com o primeiro colocado, o preço continuar acima do orçamento estimado, a empresa",["deve contratar mesmo assim, por ser o menor preço.","deve negociar com os demais licitantes, segundo a ordem inicialmente estabelecida.","deve dispensar a licitação automaticamente.","deve alterar o orçamento estimado.","deve sortear o vencedor."],1,["Preço acima do orçamento é causa de desclassificação (art. 56, IV), ressalvado o art. 34.","Art. 57, §1º.","A dispensa por preços superiores ao de mercado exige o caso do art. 29, IV, e não é automática.","A lei não autoriza ajustar o orçamento para acomodar a proposta.","Sorteio é critério de desempate."],"Lei 13.303/2016, arts. 56 e 57.")
]});
