MODS.push({n:15,t:"Compras, sourcing e gestão de contratos",fora:true,edital:"não consta por nome, mas a finalidade da ênfase inclui \"fiscalização técnica e administrativa dos contratos de bens e serviços\"",
alerta:"Complemento. A parte de conceitos (Kraljic, TCO) é da literatura; a parte de contratos usa o texto conferido da Lei 13.303. Atribuições de gestor e fiscal de contrato seguem o regulamento interno da Transpetro, que não foi lido.",
intro:"O edital descreve a atuação da ênfase como comercialização, marketing, logística e fiscalização técnica e administrativa de contratos. Este módulo conecta compras estratégicas e gestão de contratos.",
obj:["Descrever o ciclo de compras.","Aplicar a matriz de Kraljic.","Explicar custo total de propriedade (TCO) e opções de sourcing.","Reconhecer as regras de execução, alteração e responsabilização em contratos da Lei 13.303."],
secs:[
["1. Ciclo de compras e sourcing","<p>Necessidade e especificação → pesquisa e qualificação de fornecedores → cotação ou licitação → negociação → contrato ou pedido → recebimento → pagamento → avaliação do fornecedor. Decisões de <b>make or buy</b> (fazer ou comprar), <b>sourcing único, duplo ou múltiplo</b> e avaliação de desempenho (prazo, qualidade, preço, serviço). <b>Custo total de propriedade (TCO)</b> soma ao preço de compra os custos de aquisição, uso, manutenção, riscos e descarte ao longo do ciclo de vida. A Lei 13.303 valoriza o ciclo de vida do objeto (art. 31) e a maior vantagem competitiva considerando custos diretos e indiretos (art. 32, II).</p>","CHOPRA; MEINDL; MONCZKA, R. et al., <i>Purchasing and Supply Chain Management</i>; Lei 13.303/2016, arts. 31 e 32."],
["2. Matriz de Kraljic","<table><tr><th></th><th>Baixo risco de suprimento</th><th>Alto risco de suprimento</th></tr><tr><th>Alto impacto no resultado</th><td><b>Alavancagem</b>: explorar poder de compra, concorrência entre fornecedores</td><td><b>Estratégicos</b>: parcerias e contratos de longo prazo</td></tr><tr><th>Baixo impacto</th><td><b>Não críticos (rotina)</b>: simplificar, padronizar, automatizar</td><td><b>Gargalo</b>: garantir suprimento, estoques, fontes alternativas</td></tr></table>","KRALJIC, P. \"Purchasing Must Become Supply Management\", <i>Harvard Business Review</i>, 1983."],
["3. Execução do contrato na Lei 13.303","<ul><li>O contratado <b>repara os vícios</b> às suas expensas e responde por danos independentemente de culpa ou dolo (art. 76). Encargos trabalhistas, fiscais e comerciais são dele; a inadimplência <b>não transfere</b> responsabilidade à estatal (art. 77).</li><li><b>Subcontratação</b> só até o limite admitido no edital, com qualificação técnica da subcontratada (art. 78).</li><li>O contratado deve manter as condições de habilitação durante a execução (art. 69, IX).</li><li>Alterações <b>por acordo</b> (art. 72), até 25% ou 50% conforme o caso (art. 81, §1º); <b>reajuste</b> por apostila (art. 81, §7º); vedado aditivo por evento alocado ao contratado na <b>matriz de riscos</b> (art. 81, §8º).</li><li>Fiscalização e recebimento do objeto são matéria do <b>regulamento interno</b> (art. 40, VII e IX).</li><li>Descumprimento: advertência, multa e suspensão até 2 anos, com defesa prévia (arts. 82 e 83).</li></ul>","Lei 13.303/2016, arts. 40, 69, 72, 76 a 78, 81 a 83 (texto conferido)."],
["4. Fiscalização técnica e administrativa (conceitos)","<p>De modo geral: a fiscalização <b>técnica</b> verifica se o objeto atende às especificações, aos prazos e à qualidade (medições, testes, recebimento); a <b>administrativa</b> acompanha aspectos documentais e financeiros (habilitação mantida, garantias, prazos contratuais, reajustes, encargos, pagamentos e sanções). Registros formais, indicadores e níveis de serviço (SLA) sustentam medições e eventual aplicação de penalidades. A definição exata de papéis (gestor, fiscal) é do regulamento da empresa.</p>","Conceito geral de gestão de contratos; regulamento interno da empresa (não lido)."]
],
mapa:`COMPRAS E CONTRATOS
├── Ciclo de compras | make or buy | sourcing | TCO
├── Kraljic: alavancagem | estratégicos | gargalo | rotina
└── Contrato (Lei 13.303): vícios (art. 76) | encargos (art. 77) | subcontratação (art. 78)
    ├── alteração por acordo (25%/50%) | matriz de riscos: sem aditivo p/ risco do contratado
    └── sanções (arts. 82-83) | fiscalização e recebimento: regulamento (art. 40)`,
q:[
Q("Na matriz de Kraljic, os itens de alto impacto no resultado e baixo risco de suprimento, para os quais se recomenda explorar o poder de compra e a concorrência entre fornecedores, são os",["estratégicos.","de alavancagem.","gargalo.","não críticos (rotina).","obsoletos."],1,["Estratégicos têm alto impacto e alto risco.","Alavancagem: alto impacto e baixo risco.","Gargalo: baixo impacto e alto risco.","Não críticos: baixo impacto e baixo risco.","Não é categoria da matriz."],"Kraljic (1983)."),
Q("O custo total de propriedade (TCO) de um bem ou serviço corresponde",["apenas ao preço pago ao fornecedor.","ao preço de compra somado aos demais custos ao longo do ciclo de vida, como uso, manutenção, riscos e descarte.","ao custo de armazenagem.","à margem do fornecedor.","ao custo de transporte até a fábrica."],1,["O TCO vai além do preço.","Visão de ciclo de vida.","Armazenagem é apenas um componente.","Margem do fornecedor não define o TCO.","Transporte é apenas um componente."],"Monczka et al.; Lei 13.303/2016, art. 31."),
Q("Segundo o art. 77 da Lei 13.303/2016, a inadimplência do contratado quanto aos encargos trabalhistas, fiscais e comerciais",["transfere automaticamente à empresa estatal a responsabilidade pelo pagamento.","não transfere à estatal a responsabilidade por seu pagamento, nem pode onerar o objeto do contrato.","extingue o contrato de pleno direito.","autoriza a estatal a reter a garantia sem processo.","isenta o contratado de qualquer sanção."],1,["O art. 77, §1º afirma o contrário.","Art. 77, §1º.","A lei não prevê extinção automática.","Multas aplicadas exigem regular processo (art. 82, §2º).","Não isenta de sanção."],"Lei 13.303/2016, art. 77."),
Q("De acordo com a Lei 13.303/2016, é vedada a celebração de aditivos decorrentes de eventos supervenientes",["de qualquer natureza.","alocados, na matriz de riscos, como de responsabilidade da contratada.","que aumentem o preço em menos de 25%.","apenas em contratos com prazo inferior a um ano.","solicitados pelo fiscal do contrato."],1,["A lei admite aditivos em vários casos (art. 81).","Art. 81, §8º.","O percentual não é o critério do §8º.","O prazo não é o critério.","Quem solicita não é o critério."],"Lei 13.303/2016, art. 81, §8º."),
Q("Segundo o art. 78 da Lei 13.303/2016, sobre subcontratação é correto afirmar que",["é livre e sem limites em qualquer contrato.","é possível até o limite admitido pela empresa, previsto no edital, e a subcontratada deve atender às exigências de qualificação técnica relativas ao objeto subcontratado.","é sempre proibida.","pode recair sobre quem elaborou o projeto básico.","dispensa a responsabilidade do contratado."],1,["Há limite previsto no edital.","Art. 78, caput e §1º.","A lei a admite, nos limites do edital.","O art. 78, §2º veda a subcontratação de quem participou da licitação ou do projeto.","O contratado continua responsável (caput: sem prejuízo das responsabilidades)."],"Lei 13.303/2016, art. 78.")
]});
