MODS.push({n:16,t:"Comercialização de petróleo e derivados (noções)",fora:true,edital:"decorre da finalidade da ênfase (comercialização, mercados nacional e internacional); sem tópico nomeado no Anexo IV",
alerta:"Complemento. Conteúdo conceitual de mercado, sem citar preços, contratos ou políticas comerciais específicas da Transpetro ou da Petrobras (não consultei fontes sobre elas).",
intro:"Conceitos de mercado para entender como petróleo e derivados são negociados e precificados, e como a cadeia de derivados é organizada no Brasil.",
obj:["Explicar benchmarks e diferenciais de qualidade.","Distinguir mercado spot, contratos de prazo e derivativos.","Descrever a cadeia de derivados no Brasil.","Conectar comercialização a Incoterms, tributos e regulação."],
secs:[
["1. Formação de preço do petróleo","<p>Petróleo é uma <i>commodity</i> negociada com base em <b>benchmarks</b> (referências), como Brent e WTI. O preço de cada carga é o benchmark mais um <b>diferencial</b> (prêmio ou desconto) que reflete qualidade (°API, teor de enxofre), localização e custos logísticos. Em geral, petróleos mais leves (°API alto) e de menor teor de enxofre (doces) tendem a valer mais.</p>","Conceito de mercado (p. ex., THOMAS (org.), <i>Fundamentos de Engenharia de Petróleo</i>)."],
["2. Tipos de mercado e gestão de risco","<ul><li><b>Spot</b>: entrega imediata a preço do dia. <b>Contratos de prazo</b>: volumes e fórmula de preço acordados para um período.</li><li><b>Mercado futuro e derivativos</b> (futuros, opções, swaps) permitem <b>hedge</b>: reduzir a exposição a variações de preço. <b>Contango</b>: preços futuros acima do spot; <b>backwardation</b>: abaixo.</li><li>Termos comerciais (FOB, CFR, CIF) definem quem contrata frete e seguro e onde passa o risco (módulo 13).</li></ul>","Conceitos de mercado de commodities."],
["3. Derivados e margem de refino","<p>O preço dos derivados acompanha o do petróleo e o das condições de oferta e demanda de cada produto. O <b>crack spread</b> (ou margem de refino) é a diferença entre o valor dos derivados obtidos e o custo do petróleo processado. O preço na bomba inclui custos de refino ou importação, logística, distribuição e revenda, biocombustível adicionado e <b>tributos</b> (ICMS, PIS/COFINS, CIDE, módulo 6).</p>","Conceitos de mercado; módulo 6."],
["4. Cadeia no Brasil e regulação","<p>Produção e refino (ou importação) → <b>distribuição</b> (atacado, Lei 9.478, art. 6º, XX) → <b>revenda</b> (varejo, art. 6º, XXI). A política energética busca proteger o consumidor quanto a preço, qualidade e oferta e promover a <b>livre concorrência</b> (art. 1º); a ANP regula e fiscaliza. A Transpetro atua na movimentação e armazenagem (dutos, terminais, navios), sujeita às regras de acesso de terceiros (módulo 4). A <b>comercialização</b> direta de produtos relacionados ao objeto social não se submete ao capítulo de licitações da Lei 13.303 (art. 28, §3º, I).</p>","Lei 9.478/1997, arts. 1º e 6º; Lei 13.303/2016, art. 28, §3º (textos conferidos)."]
],
mapa:`COMERCIALIZAÇÃO
├── Benchmark (Brent, WTI) ± diferencial (qualidade, local, logística)
├── Spot × contratos de prazo × derivativos (hedge); contango × backwardation
├── Derivados: crack spread; tributos na formação de preço
└── Brasil: refino/importação → distribuição (atacado) → revenda (varejo); ANP`,
q:[
Q("Na comercialização internacional de petróleo, o preço de uma carga é frequentemente fixado como",["valor único e imutável, independente do mercado.","o preço de um benchmark (por exemplo, Brent) acrescido de um diferencial que reflete qualidade, localização e logística.","o custo de extração acrescido de margem fixa.","o preço do derivado mais vendido.","o preço da menor cotação no varejo."],1,["Preços seguem referências de mercado.","Benchmark mais diferencial.","O preço de mercado não se baseia só em custo de extração.","O derivado não é a base de preço do petróleo bruto.","O varejo não referencia o preço do petróleo."],"Conceito de mercado."),
Q("Em geral, um petróleo com maior grau API e menor teor de enxofre tende a",["ter menor valor de mercado.","ter maior valor de mercado, por render mais derivados nobres e exigir menos tratamento.","ser impossível de refinar.","ser classificado como pesado e azedo.","ter o mesmo valor de qualquer outro."],1,["Tende a ser mais valorizado.","Petróleo leve e doce é, em geral, mais valorizado.","É refinável.","Leve e doce é o oposto de pesado e azedo.","Qualidade influencia o diferencial de preço."],"Thomas (org.)."),
Q("Segundo a Lei 9.478/1997, a atividade de venda a varejo de combustíveis, lubrificantes e GLP envasado, exercida por postos de serviços ou revendedores, denomina-se",["distribuição.","revenda.","transferência.","estocagem.","refino."],1,["Distribuição é o atacado.","Art. 6º, XXI.","Transferência é movimentação de interesse exclusivo.","Estocagem é armazenamento.","Refino é atividade industrial."],"Lei 9.478/1997, art. 6º, XX e XXI."),
Q("Um agente utiliza contratos de mercado futuro para reduzir sua exposição às variações do preço do petróleo. Essa operação é conhecida como",["arbitragem cambial.","hedge.","alavancagem operacional.","contango.","dumping."],1,["Arbitragem busca lucro com diferença de preços.","Hedge é a proteção contra variação de preços.","Alavancagem operacional relaciona custos fixos e resultado.","Contango é uma estrutura de preços futuros acima do spot.","Dumping é venda abaixo do custo para excluir concorrentes."],"Conceitos de mercado de commodities."),
Q("A diferença entre o valor dos derivados obtidos e o custo do petróleo processado, usada como indicador de margem de refino, é chamada de",["crack spread.","contango.","royalty.","ship-or-pay.","laytime."],0,["Margem de refino.","Contango é a estrutura de preços futuros.","Royalty é participação governamental.","Ship-or-pay é modalidade contratual de terminais.","Laytime é tempo de carga e descarga no afretamento."],"Conceitos de mercado.")
]});
