MODS.push({n:17,t:"Qualidade, segurança, meio ambiente, saúde e integridade",fora:true,edital:"a finalidade da ênfase cita \"normas e procedimentos técnicos, de qualidade, segurança, meio ambiente e saúde\"",
alerta:"Complemento. Normas ISO e a Lei 12.846/2013 vêm de conhecimento prévio (não conferidas). A parte de integridade da Lei 13.303 (art. 9º) foi conferida.",
intro:"A finalidade da ênfase exige atuar em conformidade com normas de qualidade, segurança, meio ambiente e saúde (QSMS). Aqui estão as noções básicas e o tema de integridade nas estatais.",
obj:["Distinguir as normas ISO 9001, 14001 e 45001.","Explicar o ciclo PDCA.","Ordenar a hierarquia de controles de riscos.","Reconhecer as licenças ambientais.","Descrever as exigências de integridade da Lei 13.303 e a responsabilização da Lei 12.846/2013."],
secs:[
["1. Sistemas de gestão e PDCA","<ul><li><b>ISO 9001</b>: gestão da qualidade. <b>ISO 14001</b>: gestão ambiental. <b>ISO 45001</b>: gestão de saúde e segurança ocupacional.</li><li><b>PDCA</b>: Plan (planejar), Do (executar), Check (verificar), Act (agir corretivamente). Melhoria contínua.</li></ul>","ISO 9001, ISO 14001 e ISO 45001 (versões vigentes)."],
["2. Hierarquia de controles de riscos ocupacionais","<p>Do mais para o menos eficaz: <b>eliminação</b> do perigo; <b>substituição</b>; <b>controles de engenharia</b> (proteções coletivas); <b>controles administrativos</b> (procedimentos, treinamento, sinalização); <b>EPI</b> (equipamento de proteção individual).</p>","ISO 45001, item 8.1.2."],
["3. Licenciamento ambiental","<p>Fases clássicas: <b>licença prévia (LP)</b> (viabilidade e localização), <b>licença de instalação (LI)</b> (autoriza a construção) e <b>licença de operação (LO)</b> (autoriza o funcionamento). As licitações e contratos das estatais devem respeitar normas de resíduos, mitigação de danos ambientais, eficiência de energia e acessibilidade (Lei 13.303, art. 32, §1º). Em transporte marítimo, a MARPOL trata da poluição por navios (módulo 3).</p>","Resolução CONAMA 237/1997; Lei 13.303/2016, art. 32, §1º."],
["4. Integridade nas estatais (Lei 13.303, art. 9º)","<p>As estatais adotam regras de gestão de riscos e controle interno, com área de conformidade e gestão de riscos, auditoria interna e Comitê de Auditoria Estatutário. Devem elaborar e divulgar <b>Código de Conduta e Integridade</b> com: princípios e valores, prevenção de conflito de interesses e vedação a corrupção e fraude; instâncias responsáveis; <b>canal de denúncias</b>; mecanismos que impeçam <b>retaliação</b>; sanções; e <b>treinamento periódico, no mínimo anual</b>. A área de conformidade e riscos é vinculada ao diretor-presidente e liderada por diretor estatutário (§2º). A auditoria interna é vinculada ao Conselho de Administração (§3º).</p>","Lei 13.303/2016, art. 9º (texto conferido)."],
["5. Lei Anticorrupção (Lei 12.846/2013)","<p>Prevê <b>responsabilização objetiva</b>, administrativa e civil, de pessoas jurídicas pela prática de atos lesivos contra a administração pública, nacional ou estrangeira. Multa administrativa de 0,1% a 20% do faturamento bruto do último exercício anterior ao da instauração do processo, e possibilidade de <b>acordo de leniência</b>. A existência de programa de integridade é considerada na aplicação das sanções. A Lei 13.303 refere-se ao cadastro de empresas inidôneas dessa lei (art. 37).</p>","Lei 12.846/2013 (texto não verificado: confira); Lei 13.303/2016, art. 37."]
],
mapa:`QSMS E INTEGRIDADE
├── ISO 9001 (qualidade) | 14001 (ambiental) | 45001 (SSO); PDCA
├── Controles: eliminação → substituição → engenharia → administrativos → EPI
├── Licenças: LP → LI → LO
├── Lei 13.303 art. 9º: código de conduta, canal de denúncias, treinamento anual
└── Lei 12.846/2013: responsabilidade objetiva; multa 0,1%-20%; leniência`,
q:[
Q("A norma ISO 14001 trata de",["gestão da qualidade.","gestão ambiental.","gestão de saúde e segurança ocupacional.","gestão de ativos.","segurança da informação."],1,["Qualidade é ISO 9001.","ISO 14001 é a norma de sistema de gestão ambiental.","SSO é ISO 45001.","Ativos: ISO 55000.","Segurança da informação: ISO/IEC 27001."],"ISO 14001."),
Q("Na hierarquia de controles de riscos ocupacionais, a medida considerada mais eficaz é",["o fornecimento de EPI.","a eliminação do perigo.","o treinamento dos trabalhadores.","a sinalização de segurança.","a substituição de turnos."],1,["EPI é a medida menos eficaz da hierarquia.","Eliminar o perigo encabeça a hierarquia.","Treinamento é controle administrativo.","Sinalização é controle administrativo.","Não integra a hierarquia."],"ISO 45001, item 8.1.2."),
Q("No licenciamento ambiental, a licença que autoriza o funcionamento da atividade após verificada a instalação conforme o projeto é a",["licença prévia.","licença de instalação.","licença de operação.","autorização de supressão.","outorga de uso da água."],2,["A prévia aprova localização e concepção.","A de instalação autoriza a construção.","A de operação autoriza o funcionamento.","Não é a licença do rol clássico.","Não é a licença do rol clássico."],"Resolução CONAMA 237/1997."),
Q("Segundo o art. 9º da Lei 13.303/2016, o Código de Conduta e Integridade das empresas estatais deve prever, entre outros elementos,",["apenas princípios e missão da empresa.","canal de denúncias, proteção contra retaliação, sanções e treinamento periódico, no mínimo anual.","a dispensa de auditoria interna.","a vedação de canal externo de denúncias.","a subordinação da área de conformidade ao Conselho Fiscal."],1,["Há outros elementos obrigatórios.","Art. 9º, §1º, III a VI.","A auditoria interna é obrigatória (art. 9º, III).","O canal deve receber denúncias internas e externas.","A área é vinculada ao diretor-presidente (art. 9º, §2º)."],"Lei 13.303/2016, art. 9º."),
Q("A responsabilização de pessoas jurídicas prevista na Lei 12.846/2013 (Lei Anticorrupção) é",["subjetiva, exigindo prova de dolo.","objetiva, nas esferas administrativa e civil.","exclusivamente penal.","restrita a pessoas físicas.","aplicável só a empresas estrangeiras."],1,["A lei adota responsabilidade objetiva.","Responsabilização objetiva, administrativa e civil.","A lei trata de responsabilização administrativa e civil.","Refere-se a pessoas jurídicas.","Alcança pessoas jurídicas nacionais e estrangeiras."],"Lei 12.846/2013 (conferir texto).")
]});
